cat_documentation <- function(title_str, documentation_df) {
    first_element <- match(title_str, documentation_df$title)
    every_element <- grep(title_str, documentation_df$title)
    documentation_str <- character(length = 14L)
    documentation_str[01] <-
        "## generated by make_data_documentation(): do not edit by hand"
    documentation_str[02] <-
        "\n## see source in data-raw/make_data_documentation.R"
    documentation_str[03] <- documentation_title(first_element,
                                                 documentation_df)
    documentation_str[04] <- documentation_aliases(every_element,
                                                   documentation_df)
    documentation_str[05] <- documentation_section("Datasets:")
    documentation_str[06] <- documentation_datasets(every_element,
                                                     documentation_df)
    documentation_str[07] <- documentation_section("Exploratory Data Analysis:")
    documentation_str[08] <- documentation_eda(first_element, documentation_df)
    documentation_str[09] <- documentation_section("Source:")
    documentation_str[10] <- documentation_source(first_element,
                                                  documentation_df)

    documentation_str[11] <- documentation_seealso(every_element,
                                                  documentation_df)
    documentation_str[12] <- documentation_examples(first_element,
                                                    documentation_df)
    documentation_str[13] <- documentation_name(first_element, documentation_df)
    documentation_str[14] <- "\nNULL\n"
    documentation_filename(first_element, documentation_df) %>%
    cat(documentation_str, file = .)
}
