make_metadata_documentation <- function() {
    template_csv <- read_csv("./inst/extdata/template.csv")
    documentation_str <- character(length = 7L)
    documentation_str[1] <-
        "## generated by make_metadata_documentation(): do not edit by hand"
    documentation_str[2] <-
        "\n## see source in data-raw/make_metadata_documentation.R"
    documentation_str[3] <-
        "\n#' Combined metadata of all studies in curatedMetagenomicData\n#'"
    documentation_str[4] <-
        "\n#' The combined sample level metadata of all studies in curatedMetagenomicData.\n#'"
    documentation_str[5] <- documentation_format(template_csv)
    documentation_str[6] <-
        "\n#' @source See dataset specific help functions for source information"
    documentation_str[7] <- "\n\"combined_metadata\"\n"
    cat(documentation_str, file = "./R/combined_metadata.R")
}
