---
title: "curatedMetagenomicData"
author:
- name: Lucas Schiffer, MPH
  affiliation: 
  - Section of Computational Biomedicine, Boston University School of Medicine,
    Boston, MA, U.S.A.
  email: schifferl@bu.edu
package: curatedMetagenomicData
abstract: >
  The curatedMetagenomicData package provides microbial taxonomic, functional,
  and gene marker abundance for samples collected from different body sites.
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{curatedMetagenomicData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r}
library(curatedMetagenomicData)
```

# Sample Metadata

```{r}
dplyr::glimpse(sampleMetadata)
```

# Metagenomic Data

```{r}
curatedMetagenomicData("AsnicarF_2017.relative_abundance", dryrun = FALSE)
```

# Multiple (Down)loads

```{r}
curatedMetagenomicData("AsnicarF_2017.pathway", print = FALSE) %>%
  sapply(curatedMetagenomicData, dryrun = FALSE)
```

# Session Info {.unnumbered}

```{r, echo = FALSE}
sessionInfo()
```
