---
title: "Version Three"
---

The release of curatedMetagenomicData version 3.0.0 (we skipped version 2.0.0) is a long awaited and major milestone for the whole team - it has been years in the making and took countless hours of work across many time zones. We are very proud of the product and want to let you know what has changed and why you should update to the latest (and greatest) version. However, we know that some of the changes might be big adjustments and we've made sure that curatedMetagenomicData version 1.20.0 will remain installable for the foreseeable future.

Next, just to be clear and avoid confusion, we skipped version 2.0.0 and for good reason. The data in curatedMetagenomicData version 1.0.0 (released in 2017) came from MetaPhlAn2 and HUMAnN2; the data in curatedMetagenomicData version 3.0.0 (released in 2021) comes from MetaPhlAn3 and HUMAnN3. The skipping of version 2.0.0 and release of 3.0.0 instead was done to align our version numbers with MetaPhlAn3 and HUMAnN3 - it may cause a bit of confusion at first but should ultimately lead to more clarity as we stay in step with their versions. Yes, the same would have been desirable for the first release, but hindsight is 20/20 and we just didn't think of it.

Now, the reasons to upgrade to curatedMetagenomicData version 3.0.0 are numerous, but at the top of the list is that curatedMetagenomicData now uses appropriate modern Bioconductor data structures (SummarizedExperiment and TreeSummarizedExperiment). The outdated ExpressionSet objects that were previously returned have been removed, and methods that operated on them have moved directly to defunct status. The same has happened to all named accessors (e.g. `HMP_2012.pathcoverage.stool()`) to make the package easier to maintain and document. The `curatedMetagenomicData()` method replaces all named accessors and it is an excellent method that you may already be familiar with - it is another epic upgrade in version 3.0.0. The method (and the whole code base really) has been completely refactored for accuracy and efficency; `curatedMetagenomicData()` is now the primary (and only) means to access data. It quickly returns list containing SummarizedExperiment and TreeSummarizedExperiment elements that can be passed on to other methods.

The first of these is `mergeData()`, which is also a complete refactoring of the older method, that can be used to join to studies of the same data type together. This is likely useful in the context of meta-analysis for analysis across entire studies, where a single unified SummarizedExperiment or TreeSummarizedExperiment can be used to quickly quantify differences in effect size across studies. However, if analysis across individual samples (e.g. mega-analysis) is desired, `returnSamples()` will now accommodate returns based on a subset of rows and columns in `sampleMetadata`. We suspect this was a feature frequently implemented by users and have now included it in the package for consistency of methodology. Not only does it allow users to get exactly the samples they want, but it allows for the creation of user-defined or calculated metadata variables that will propagate to SummarizedExperiment or TreeSummarizedExperiment objects that are returned.

Otherwise, there are a few last things for users to know. We have almost doubled the number of samples in the package: curatedMetagenomicData now contains 20,283 samples from 86 studies, with a total of 10,084 samples added since Bioconductor 3.10 (October 2019). The updating of manually curated sample metadata from the curation effort has been automated and sample metadata always stays up to date now with weekly updates. The `sampleMetadata` object replaces the `combined_metadata` object; the `combined_metadata` object will be removed in the next release. Finally, with these and other internal infrastructure changes we are now ready for the future and any change in data structure it might bring. We hope you like the updates as much as we do and will understand they were necessary - from the entire team, thank you for using curatedMetagenomicData.
