write_documentation <- function(documentation_df) {
    documentation_str <- character(length = 12L)
    documentation_str[1] <-
        "# generated by make_documentation(): do not edit by hand"
    documentation_str[2] <-
        "\n# see source in inst/scripts/make-documentation.R"
    title_str <- unique(documentation_df$title)
    for (i in title_str) {
        first_element <- match(i, documentation_df$title)
        every_element <- grep(i, documentation_df$title)
        documentation_str[3] <- documentation_title(first_element,
                                                   documentation_df)
        documentation_str[4] <- documentation_aliases(every_element,
                                                       documentation_df)
        documentation_str[5] <- documentation_section("Datasets")
        documentation_str[6] <- documentation_subsection(every_element,
                                                         documentation_df)
        documentation_str[7] <- documentation_subsection(first_element,
                                                         documentation_df)
        documentation_str[8] <- documentation_source(first_element,
                                                     documentation_df)
        documentation_str[9] <- documentation_seealso(every_element,
                                                         documentation_df)
        documentation_str[10] <- documentation_name(first_element,
                                                     documentation_df)
        documentation_str[11] <- "\nNULL"
        documentation_str[12] <- "\n"
        documentation_filename(first_element, documentation_df) %>%
        cat(documentation_str, file = .)
    }
}
