## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the AsnicarF_2017 study
#' 
#' @aliases AsnicarF_2017.genefamilies_relab.milk AsnicarF_2017.genefamilies_relab.stool AsnicarF_2017.marker_abundance.milk AsnicarF_2017.marker_abundance.stool AsnicarF_2017.marker_presence.milk AsnicarF_2017.marker_presence.stool AsnicarF_2017.metaphlan_bugs_list.milk AsnicarF_2017.metaphlan_bugs_list.stool AsnicarF_2017.pathabundance_relab.milk AsnicarF_2017.pathabundance_relab.stool AsnicarF_2017.pathcoverage.milk AsnicarF_2017.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{AsnicarF_2017.genefamilies_relab.milk}{
#'    An ExpressionSet with 8 samples and 752,977 features specific to the milk body site
#' }
#'
#' \subsection{AsnicarF_2017.genefamilies_relab.stool}{
#'    An ExpressionSet with 16 samples and 752,977 features specific to the stool body site
#' }
#'
#' \subsection{AsnicarF_2017.marker_abundance.milk}{
#'    An ExpressionSet with 8 samples and 53,228 features specific to the milk body site
#' }
#'
#' \subsection{AsnicarF_2017.marker_abundance.stool}{
#'    An ExpressionSet with 16 samples and 53,228 features specific to the stool body site
#' }
#'
#' \subsection{AsnicarF_2017.marker_presence.milk}{
#'    An ExpressionSet with 8 samples and 50,192 features specific to the milk body site
#' }
#'
#' \subsection{AsnicarF_2017.marker_presence.stool}{
#'    An ExpressionSet with 16 samples and 50,192 features specific to the stool body site
#' }
#'
#' \subsection{AsnicarF_2017.metaphlan_bugs_list.milk}{
#'    An ExpressionSet with 8 samples and 799 features specific to the milk body site
#' }
#'
#' \subsection{AsnicarF_2017.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 16 samples and 799 features specific to the stool body site
#' }
#'
#' \subsection{AsnicarF_2017.pathabundance_relab.milk}{
#'    An ExpressionSet with 8 samples and 9,274 features specific to the milk body site
#' }
#'
#' \subsection{AsnicarF_2017.pathabundance_relab.stool}{
#'    An ExpressionSet with 16 samples and 9,274 features specific to the stool body site
#' }
#'
#' \subsection{AsnicarF_2017.pathcoverage.milk}{
#'    An ExpressionSet with 8 samples and 9,274 features specific to the milk body site
#' }
#'
#' \subsection{AsnicarF_2017.pathcoverage.stool}{
#'    An ExpressionSet with 16 samples and 9,274 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{AsnicarF_2017_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{AsnicarF_2017_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{AsnicarF_2017_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{AsnicarF_2017_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{AsnicarF_2017_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Studying Vertical Microbiome Transmission from Mothers to Infants by Strain-Level Metagenomic Profiling.
#' }
#'
#' \subsection{Author}{
#'    Asnicar F, Manara S, Zolfo M, Truong DT, Scholz M, Armanini F, Ferretti P, Gorfer V, Pedrotti A, Tett A, Segata N
#' }
#'
#' \subsection{Lab}{
#'    Centre for Integrative Biology, University of Trento, Trento, Italy.
#' }
#'
#' \subsection{PMID}{
#'    28144631
#' }
#' 
#' @examples AsnicarF_2017.metaphlan_bugs_list.milk()
#' 
#' @name AsnicarF_2017 
NULL
 