## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the BritoIL_2016 study
#' 
#' @aliases BritoIL_2016.genefamilies_relab.oralcavity BritoIL_2016.genefamilies_relab.stool BritoIL_2016.marker_abundance.oralcavity BritoIL_2016.marker_abundance.stool BritoIL_2016.marker_presence.oralcavity BritoIL_2016.marker_presence.stool BritoIL_2016.metaphlan_bugs_list.oralcavity BritoIL_2016.metaphlan_bugs_list.stool BritoIL_2016.pathabundance_relab.oralcavity BritoIL_2016.pathabundance_relab.stool BritoIL_2016.pathcoverage.oralcavity BritoIL_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{BritoIL_2016.genefamilies_relab.oralcavity}{
#'    An ExpressionSet with 140 samples and 1,825,268 features specific to the oralcavity body site
#' }
#'
#' \subsection{BritoIL_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 172 samples and 1,825,268 features specific to the stool body site
#' }
#'
#' \subsection{BritoIL_2016.marker_abundance.oralcavity}{
#'    An ExpressionSet with 140 samples and 162,905 features specific to the oralcavity body site
#' }
#'
#' \subsection{BritoIL_2016.marker_abundance.stool}{
#'    An ExpressionSet with 172 samples and 162,905 features specific to the stool body site
#' }
#'
#' \subsection{BritoIL_2016.marker_presence.oralcavity}{
#'    An ExpressionSet with 140 samples and 156,452 features specific to the oralcavity body site
#' }
#'
#' \subsection{BritoIL_2016.marker_presence.stool}{
#'    An ExpressionSet with 172 samples and 156,452 features specific to the stool body site
#' }
#'
#' \subsection{BritoIL_2016.metaphlan_bugs_list.oralcavity}{
#'    An ExpressionSet with 140 samples and 1,864 features specific to the oralcavity body site
#' }
#'
#' \subsection{BritoIL_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 172 samples and 1,864 features specific to the stool body site
#' }
#'
#' \subsection{BritoIL_2016.pathabundance_relab.oralcavity}{
#'    An ExpressionSet with 140 samples and 22,539 features specific to the oralcavity body site
#' }
#'
#' \subsection{BritoIL_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 172 samples and 22,539 features specific to the stool body site
#' }
#'
#' \subsection{BritoIL_2016.pathcoverage.oralcavity}{
#'    An ExpressionSet with 140 samples and 22,539 features specific to the oralcavity body site
#' }
#'
#' \subsection{BritoIL_2016.pathcoverage.stool}{
#'    An ExpressionSet with 172 samples and 22,539 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Mobile genes in the human microbiome are structured from global to individual scales.
#' }
#'
#' \subsection{Author}{
#'    Brito IL, Yilmaz S, Huang K, Xu L, Jupiter SD, Jenkins AP, Naisilisili W, Tamminen M, Smillie CS, Wortman JR, Birren BW, Xavier RJ, Blainey PC, Singh AK, Gevers D, Alm EJ
#' }
#'
#' \subsection{Lab}{
#'    [1] Department of Biological Engineering, Massachusetts Institute of Technology, Cambridge, MA., [2] Broad Institute of MIT and Harvard, Cambridge, MA., [3] Sandia National Laboratories, Livermore, CA., [4] Wildlife Conservation Society, Suva, Fiji., [5] Edith Cowan University, Western Australia., [6] University of Helsinki, Helsinki, Finland., [7] Massachusetts General Hospital, Boston, MA., [8] Center for Microbiome, Informatics and Therapeutics, Massachusetts Institute of Technology, Cambridge, MA.
#' }
#'
#' \subsection{PMID}{
#'    27409808
#' }
#' 
#' @examples `BritoIL_2016.metaphlan_bugs_list.oralcavity`()
#' 
#' @name BritoIL_2016 
NULL
