## generated by make_data_documentation(): do not edit by hand
## see source in data-raw/make_data_documentation.R
#' Data from the Castro-NallarE_2015 study
#'
#' @aliases Castro-NallarE_2015.genefamilies_relab.oralcavity Castro-NallarE_2015.marker_abundance.oralcavity Castro-NallarE_2015.marker_presence.oralcavity Castro-NallarE_2015.metaphlan_bugs_list.oralcavity Castro-NallarE_2015.pathabundance_relab.oralcavity Castro-NallarE_2015.pathcoverage.oralcavity Castro_NallarE_2015 Castro_NallarE_2015.genefamilies_relab.oralcavity Castro_NallarE_2015.marker_abundance.oralcavity Castro_NallarE_2015.marker_presence.oralcavity Castro_NallarE_2015.metaphlan_bugs_list.oralcavity Castro_NallarE_2015.pathabundance_relab.oralcavity Castro_NallarE_2015.pathcoverage.oralcavity
#' @details Note that Castro_NallarE_2015 is deprecated, use Castro-NallarE_2015 instead.
#'
#' @section Datasets:
#'
#' \subsection{Castro-NallarE_2015.genefamilies_relab.oralcavity}{
#'    An ExpressionSet with 32 samples and 588,014 features specific to the oralcavity body site
#' }
#'
#' \subsection{Castro-NallarE_2015.marker_abundance.oralcavity}{
#'    An ExpressionSet with 32 samples and 51,679 features specific to the oralcavity body site
#' }
#'
#' \subsection{Castro-NallarE_2015.marker_presence.oralcavity}{
#'    An ExpressionSet with 32 samples and 49,093 features specific to the oralcavity body site
#' }
#'
#' \subsection{Castro-NallarE_2015.metaphlan_bugs_list.oralcavity}{
#'    An ExpressionSet with 32 samples and 755 features specific to the oralcavity body site
#' }
#'
#' \subsection{Castro-NallarE_2015.pathabundance_relab.oralcavity}{
#'    An ExpressionSet with 32 samples and 9,237 features specific to the oralcavity body site
#' }
#'
#' \subsection{Castro-NallarE_2015.pathcoverage.oralcavity}{
#'    An ExpressionSet with 32 samples and 9,237 features specific to the oralcavity body site
#' }
#'
#' @section Source:
#'
#' \subsection{Title}{
#'    Composition, taxonomy and functional diversity of the oropharynx microbiome in individuals with schizophrenia and controls.
#' }
#'
#' \subsection{Author}{
#'    Castro-Nallar E, Bendall ML, Pérez-Losada M, Sabuncyan S, Severance EG, Dickerson FB, Schroeder JR, Yolken RH, Crandall KA
#' }
#'
#' \subsection{Lab}{
#'    [1] Computational Biology Institute, George Washington University , Ashburn, VA , USA ; Center for Bioinformatics and Integrative Biology, Universidad Andres Bello, Facultad de Ciencias Biologicas , Santiago , Chile., [2] Computational Biology Institute, George Washington University , Ashburn, VA , USA., [3] Computational Biology Institute, George Washington University , Ashburn, VA , USA ; CIBIO-InBIO, Centro de Investigacao em Biodiversidade e Recursos Geneticos, Universidade do Porto , Vairao , USA ; Division of Emergency Medicine, Children's National Medical Center , Washington, D.C. , USA., [4] Stanley Neurovirology Laboratory, Johns Hopkins School of Medicine , Baltimore, MD , USA., [5] Sheppard Pratt Hospital , Baltimore, MD , USA., [6] Schroeder Statistical Consulting LLC , Ellicott City, MD , USA.
#' }
#'
#' \subsection{PMID}{
#'    26336637
#' }
#'
#' @examples `Castro-NallarE_2015.metaphlan_bugs_list.oralcavity`()
#'
#' @name Castro-NallarE_2015
NULL
