## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the ChngKR_2016 study
#' 
#' @aliases ChngKR_2016.genefamilies_relab.skin ChngKR_2016.marker_abundance.skin ChngKR_2016.marker_presence.skin ChngKR_2016.metaphlan_bugs_list.skin ChngKR_2016.pathabundance_relab.skin ChngKR_2016.pathcoverage.skin 
#' 
#' @section Datasets: 
#' 
#' \subsection{ChngKR_2016.genefamilies_relab.skin}{
#'    An ExpressionSet with 78 samples and 823,859 features specific to the skin body site
#' }
#'
#' \subsection{ChngKR_2016.marker_abundance.skin}{
#'    An ExpressionSet with 78 samples and 89,597 features specific to the skin body site
#' }
#'
#' \subsection{ChngKR_2016.marker_presence.skin}{
#'    An ExpressionSet with 78 samples and 85,656 features specific to the skin body site
#' }
#'
#' \subsection{ChngKR_2016.metaphlan_bugs_list.skin}{
#'    An ExpressionSet with 78 samples and 1,219 features specific to the skin body site
#' }
#'
#' \subsection{ChngKR_2016.pathabundance_relab.skin}{
#'    An ExpressionSet with 78 samples and 10,995 features specific to the skin body site
#' }
#'
#' \subsection{ChngKR_2016.pathcoverage.skin}{
#'    An ExpressionSet with 78 samples and 10,995 features specific to the skin body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{ChngKR_2016_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ChngKR_2016_BMI.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ChngKR_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ChngKR_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ChngKR_2016_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ChngKR_2016_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Whole metagenome profiling reveals skin microbiome-dependent susceptibility to atopic dermatitis flare.
#' }
#'
#' \subsection{Author}{
#'    Chng KR, Tay AS, Li C, Ng AH, Wang J, Suri BK, Matta SA, McGovern N, Janela B, Wong XF, Sio YY, Au BV, Wilm A, De Sessions PF, Lim TC, Tang MB, Ginhoux F, Connolly JE, Lane EB, Chew FT, Common JE, Nagarajan N
#' }
#'
#' \subsection{Lab}{
#'    Genome Institute of Singapore, Singapore 138672, Singapore.
#' }
#'
#' \subsection{PMID}{
#'    27562258
#' }
#' 
#' @examples ChngKR_2016.genefamilies_relab.skin()
#' 
#' @name ChngKR_2016 
NULL
 