## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the CosteaPI_2017 study
#' 
#' @aliases CosteaPI_2017.genefamilies_relab.stool CosteaPI_2017.marker_abundance.stool CosteaPI_2017.marker_presence.stool CosteaPI_2017.metaphlan_bugs_list.stool CosteaPI_2017.pathabundance_relab.stool CosteaPI_2017.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{CosteaPI_2017.genefamilies_relab.stool}{
#'    An ExpressionSet with 279 samples and 1,679,856 features specific to the stool body site
#' }
#'
#' \subsection{CosteaPI_2017.marker_abundance.stool}{
#'    An ExpressionSet with 279 samples and 118,830 features specific to the stool body site
#' }
#'
#' \subsection{CosteaPI_2017.marker_presence.stool}{
#'    An ExpressionSet with 279 samples and 113,692 features specific to the stool body site
#' }
#'
#' \subsection{CosteaPI_2017.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 279 samples and 1,337 features specific to the stool body site
#' }
#'
#' \subsection{CosteaPI_2017.pathabundance_relab.stool}{
#'    An ExpressionSet with 279 samples and 13,913 features specific to the stool body site
#' }
#'
#' \subsection{CosteaPI_2017.pathcoverage.stool}{
#'    An ExpressionSet with 279 samples and 13,913 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Subspecies in the global human gut microbiome.
#' }
#'
#' \subsection{Author}{
#'    Costea PI, Coelho LP, Sunagawa S, Munch R, Huerta-Cepas J, Forslund K, Hildebrand F, Kushugulova A, Zeller G, Bork P
#' }
#'
#' \subsection{Lab}{
#'    [1] Structural and Computational Biology Unit, European Molecular Biology Laboratory, Heidelberg, Germany., [2] Department of Biology, Institute of Microbiology, ETH Zurich, Zurich, Switzerland., [3] Center for Life Sciences, Nazarbayev University, Astana, Kazakhstan., [4] Structural and Computational Biology Unit, European Molecular Biology Laboratory, Heidelberg, Germany zeller@embl.de bork@embl.de., [5] Max-Delbruck-Centre for Molecular Medicine, Berlin, Germany., [6] Molecular Medicine Partnership Unit, Heidelberg, Germany., [7] Department of Bioinformatics, Biocenter, University of Wurzburg, Wurzburg, Germany.
#' }
#'
#' \subsection{PMID}{
#'    29242367
#' }
#' 
#' @examples CosteaPI_2017.metaphlan_bugs_list.stool()
#' 
#' @name CosteaPI_2017 
NULL
