## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the DhakanDB_2019 study
#' 
#' @aliases DhakanDB_2019.genefamilies_relab.stool DhakanDB_2019.marker_abundance.stool DhakanDB_2019.marker_presence.stool DhakanDB_2019.metaphlan_bugs_list.stool DhakanDB_2019.pathabundance_relab.stool DhakanDB_2019.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{DhakanDB_2019.genefamilies_relab.stool}{
#'    An ExpressionSet with 110 samples and 925,244 features specific to the stool body site
#' }
#'
#' \subsection{DhakanDB_2019.marker_abundance.stool}{
#'    An ExpressionSet with 110 samples and 63,517 features specific to the stool body site
#' }
#'
#' \subsection{DhakanDB_2019.marker_presence.stool}{
#'    An ExpressionSet with 110 samples and 59,670 features specific to the stool body site
#' }
#'
#' \subsection{DhakanDB_2019.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 110 samples and 768 features specific to the stool body site
#' }
#'
#' \subsection{DhakanDB_2019.pathabundance_relab.stool}{
#'    An ExpressionSet with 110 samples and 5,480 features specific to the stool body site
#' }
#'
#' \subsection{DhakanDB_2019.pathcoverage.stool}{
#'    An ExpressionSet with 110 samples and 5,480 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    The unique composition of Indian gut microbiome, gene catalogue, and associated fecal metabolome deciphered using multi-omics approaches.
#' }
#'
#' \subsection{Author}{
#'    Dhakan DB, Maji A, Sharma AK, Saxena R, Pulikkan J, Grace T, Gomez A, Scaria J, Amato KR, Sharma VK
#' }
#'
#' \subsection{Lab}{
#'    [1] Metagenomics and Systems Biology Laboratory, Department of Biological Sciences, Indian Institute of Science Education and Research Bhopal, Bhauri, Madhya Pradesh, 462066, India., [2] Department of Genomic Science, Central University of Kerala, Periye Post, Kasargod, Kerala, 671316, India., [3] Division of Biology, Kansas State University, 116 Ackert Hall, Manhattan, Kansas, KS 66506, USA., [4] Microbiomics Laboratory, Department of Animal Science, University of Minnesota, 1988 Fitch Avenue, Minnesota, MN 55108, USA., [5] Animal Disease Research &amp; Diagnostic Laboratory, Veterinary and Biomedical Sciences Department, South Dakota State University, Brookings, South Dakota, SD 57007, USA., [6] Department of Anthropology, Northwestern University, 1810 Hinman Avenue, Evanston, Illinois, IL 60208, USA.
#' }
#'
#' \subsection{PMID}{
#'    30698687
#' }
#' 
#' @examples DhakanDB_2019.metaphlan_bugs_list.stool()
#' 
#' @name DhakanDB_2019 
NULL
