## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the FengQ_2015 study
#' 
#' @aliases FengQ_2015.genefamilies_relab.stool FengQ_2015.marker_abundance.stool FengQ_2015.marker_presence.stool FengQ_2015.metaphlan_bugs_list.stool FengQ_2015.pathabundance_relab.stool FengQ_2015.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{FengQ_2015.genefamilies_relab.stool}{
#'    An ExpressionSet with 154 samples and 1,627,981 features specific to the stool body site
#' }
#'
#' \subsection{FengQ_2015.marker_abundance.stool}{
#'    An ExpressionSet with 154 samples and 140,519 features specific to the stool body site
#' }
#'
#' \subsection{FengQ_2015.marker_presence.stool}{
#'    An ExpressionSet with 154 samples and 130,216 features specific to the stool body site
#' }
#'
#' \subsection{FengQ_2015.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 154 samples and 1,547 features specific to the stool body site
#' }
#'
#' \subsection{FengQ_2015.pathabundance_relab.stool}{
#'    An ExpressionSet with 154 samples and 16,866 features specific to the stool body site
#' }
#'
#' \subsection{FengQ_2015.pathcoverage.stool}{
#'    An ExpressionSet with 154 samples and 16,866 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Gut microbiome development along the colorectal adenoma-carcinoma sequence.
#' }
#'
#' \subsection{Author}{
#'    Feng Q, Liang S, Jia H, Stadlmayr A, Tang L, Lan Z, Zhang D, Xia H, Xu X, Jie Z, Su L, Li X, Li X, Li J, Xiao L, Huber-Schönauer U, Niederseer D, Xu X, Al-Aama JY, Yang H, Wang J, Kristiansen K, Arumugam M, Tilg H, Datz C, Wang J
#' }
#'
#' \subsection{Lab}{
#'    [1] 1] BGI-Shenzhen, Shenzhen 518083, China [2] Department of Biology, University of Copenhagen, Ole Maaloes Vej 5, 2200 Copenhagen, Denmark., [2] 1] BGI-Shenzhen, Shenzhen 518083, China [2] School of Bioscience and Biotechnology, South China University of Technology, Guangzhou 510006, China., [3] BGI-Shenzhen, Shenzhen 518083, China., [4] Department of Internal Medicine, Hospital Oberndorf, Teaching Hospital of the Paracelsus Private University of Salzburg, Paracelsusstrasse 37, 5110 Oberndorf, Austria., [5] 1] BGI-Shenzhen, Shenzhen 518083, China [2] School of Bioscience and Biotechnology, South China University of Technology, Guangzhou 510006, China [3] BGI Hong Kong Research Institute, Hong Kong, China., [6] 1] BGI-Shenzhen, Shenzhen 518083, China [2] Princess Al Jawhara Center of Excellence in the Research of Hereditary Disorders, King Abdulaziz University, Jeddah 21589, Saudi Arabia., [7] 1] BGI-Shenzhen, Shenzhen 518083, China [2] The Novo Nordisk Foundation Center for Basic Metabolic Research, Faculty of Health and Medical Sciences, University of Copenhagen, 2200 Copenhagen, Denmark., [8] First Department of Internal Medicine, Medical University Innsbruck, Anichstrasse 35, 6020 Innsbruck, Austria., [9] 1] BGI-Shenzhen, Shenzhen 518083, China [2] Department of Biology, University of Copenhagen, Ole Maaloes Vej 5, 2200 Copenhagen, Denmark [3] Princess Al Jawhara Center of Excellence in the Research of Hereditary Disorders, King Abdulaziz University, Jeddah 21589, Saudi Arabia [4] Macau University of Science and Technology, Avenida Wai long, Taipa, Macau 999078, China.
#' }
#'
#' \subsection{PMID}{
#'    25758642
#' }
#' 
#' @examples FengQ_2015.metaphlan_bugs_list.stool()
#' 
#' @name FengQ_2015 
NULL
