## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the FerrettiP_2018 study
#' 
#' @aliases FerrettiP_2018.genefamilies_relab.oralcavity FerrettiP_2018.genefamilies_relab.skin FerrettiP_2018.genefamilies_relab.stool FerrettiP_2018.genefamilies_relab.vagina FerrettiP_2018.marker_abundance.oralcavity FerrettiP_2018.marker_abundance.skin FerrettiP_2018.marker_abundance.stool FerrettiP_2018.marker_abundance.vagina FerrettiP_2018.marker_presence.oralcavity FerrettiP_2018.marker_presence.skin FerrettiP_2018.marker_presence.stool FerrettiP_2018.marker_presence.vagina FerrettiP_2018.metaphlan_bugs_list.oralcavity FerrettiP_2018.metaphlan_bugs_list.skin FerrettiP_2018.metaphlan_bugs_list.stool FerrettiP_2018.metaphlan_bugs_list.vagina FerrettiP_2018.pathabundance_relab.oralcavity FerrettiP_2018.pathabundance_relab.skin FerrettiP_2018.pathabundance_relab.stool FerrettiP_2018.pathabundance_relab.vagina FerrettiP_2018.pathcoverage.oralcavity FerrettiP_2018.pathcoverage.skin FerrettiP_2018.pathcoverage.stool FerrettiP_2018.pathcoverage.vagina 
#' 
#' @section Datasets: 
#' 
#' \subsection{FerrettiP_2018.genefamilies_relab.oralcavity}{
#'    An ExpressionSet with 62 samples and 1,681,365 features specific to the oralcavity body site
#' }
#'
#' \subsection{FerrettiP_2018.genefamilies_relab.skin}{
#'    An ExpressionSet with 15 samples and 1,681,365 features specific to the skin body site
#' }
#'
#' \subsection{FerrettiP_2018.genefamilies_relab.stool}{
#'    An ExpressionSet with 119 samples and 1,681,365 features specific to the stool body site
#' }
#'
#' \subsection{FerrettiP_2018.genefamilies_relab.vagina}{
#'    An ExpressionSet with 19 samples and 1,681,365 features specific to the vagina body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_abundance.oralcavity}{
#'    An ExpressionSet with 62 samples and 134,155 features specific to the oralcavity body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_abundance.skin}{
#'    An ExpressionSet with 15 samples and 134,155 features specific to the skin body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_abundance.stool}{
#'    An ExpressionSet with 119 samples and 134,155 features specific to the stool body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_abundance.vagina}{
#'    An ExpressionSet with 19 samples and 134,155 features specific to the vagina body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_presence.oralcavity}{
#'    An ExpressionSet with 62 samples and 127,110 features specific to the oralcavity body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_presence.skin}{
#'    An ExpressionSet with 15 samples and 127,110 features specific to the skin body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_presence.stool}{
#'    An ExpressionSet with 119 samples and 127,110 features specific to the stool body site
#' }
#'
#' \subsection{FerrettiP_2018.marker_presence.vagina}{
#'    An ExpressionSet with 19 samples and 127,110 features specific to the vagina body site
#' }
#'
#' \subsection{FerrettiP_2018.metaphlan_bugs_list.oralcavity}{
#'    An ExpressionSet with 62 samples and 1,749 features specific to the oralcavity body site
#' }
#'
#' \subsection{FerrettiP_2018.metaphlan_bugs_list.skin}{
#'    An ExpressionSet with 15 samples and 1,749 features specific to the skin body site
#' }
#'
#' \subsection{FerrettiP_2018.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 119 samples and 1,749 features specific to the stool body site
#' }
#'
#' \subsection{FerrettiP_2018.metaphlan_bugs_list.vagina}{
#'    An ExpressionSet with 19 samples and 1,749 features specific to the vagina body site
#' }
#'
#' \subsection{FerrettiP_2018.pathabundance_relab.oralcavity}{
#'    An ExpressionSet with 62 samples and 19,926 features specific to the oralcavity body site
#' }
#'
#' \subsection{FerrettiP_2018.pathabundance_relab.skin}{
#'    An ExpressionSet with 15 samples and 19,926 features specific to the skin body site
#' }
#'
#' \subsection{FerrettiP_2018.pathabundance_relab.stool}{
#'    An ExpressionSet with 119 samples and 19,926 features specific to the stool body site
#' }
#'
#' \subsection{FerrettiP_2018.pathabundance_relab.vagina}{
#'    An ExpressionSet with 19 samples and 19,926 features specific to the vagina body site
#' }
#'
#' \subsection{FerrettiP_2018.pathcoverage.oralcavity}{
#'    An ExpressionSet with 62 samples and 19,926 features specific to the oralcavity body site
#' }
#'
#' \subsection{FerrettiP_2018.pathcoverage.skin}{
#'    An ExpressionSet with 15 samples and 19,926 features specific to the skin body site
#' }
#'
#' \subsection{FerrettiP_2018.pathcoverage.stool}{
#'    An ExpressionSet with 119 samples and 19,926 features specific to the stool body site
#' }
#'
#' \subsection{FerrettiP_2018.pathcoverage.vagina}{
#'    An ExpressionSet with 19 samples and 19,926 features specific to the vagina body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Mother-to-Infant Microbial Transmission from Different Body Sites Shapes the Developing Infant Gut Microbiome.
#' }
#'
#' \subsection{Author}{
#'    Ferretti P, Pasolli E, Tett A, Asnicar F, Gorfer V, Fedi S, Armanini F, Truong DT, Manara S, Zolfo M, Beghini F, Bertorelli R, De Sanctis V, Bariletti I, Canto R, Clementi R, Cologna M, Crifò T, Cusumano G, Gottardi S, Innamorati C, Masè C, Postai D, Savoi D, Duranti S, Lugli GA, Mancabelli L, Turroni F, Ferrario C, Milani C, Mangifesta M, Anzalone R, Viappiani A, Yassour M, Vlamakis H, Xavier R, Collado CM, Koren O, Tateo S, Soffiati M, Pedrotti A, Ventura M, Huttenhower C, Bork P, Segata N
#' }
#'
#' \subsection{Lab}{
#'    [1] Centre for Integrative Biology, University of Trento, 38123 Trento, Italy; European Molecular Biology Laboratory, Structural and Computational Biology Unit, 69117 Heidelberg, Germany., [2] Centre for Integrative Biology, University of Trento, 38123 Trento, Italy., [3] Azienda Provinciale per i Servizi Sanitari, 38123 Trento, Italy., [4] NGS Facility, Laboratory of Biomolecular Sequence and Structure Analysis for Health, Centre for Integrative Biology, University of Trento, 38123 Trento, Italy., [5] Laboratory of Probiogenomics, Department of Chemistry, Life Sciences and Environmental Sustainability, University of Parma, 43124 Parma, Italy., [6] Laboratory of Probiogenomics, Department of Chemistry, Life Sciences and Environmental Sustainability, University of Parma, 43124 Parma, Italy; GenProbio srl, 43124 Parma, Italy., [7] GenProbio srl, 43124 Parma, Italy., [8] Broad Institute of MIT and Harvard, Cambridge, MA 02142, USA., [9] Institute of Agrochemistry and Food Technology, National Research Council, Paterna, 46980 Valencia, Spain., [10] Faculty of Medicine, Bar Ilan University, Safed 1311502, Israel., [11] Broad Institute of MIT and Harvard, Cambridge, MA 02142, USA; Department of Biostatistics, Harvard T.H. Chan School of Public Health, Boston, MA 02115, USA., [12] European Molecular Biology Laboratory, Structural and Computational Biology Unit, 69117 Heidelberg, Germany., [13] Centre for Integrative Biology, University of Trento, 38123 Trento, Italy. Electronic address: nicola.segata@unitn.it.
#' }
#'
#' \subsection{PMID}{
#'    30001516
#' }
#' 
#' @examples FerrettiP_2018.metaphlan_bugs_list.oralcavity()
#' 
#' @name FerrettiP_2018 
NULL
