## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the HanniganGD_2017 study
#' 
#' @aliases HanniganGD_2017.genefamilies_relab.stool HanniganGD_2017.marker_abundance.stool HanniganGD_2017.marker_presence.stool HanniganGD_2017.metaphlan_bugs_list.stool HanniganGD_2017.pathabundance_relab.stool HanniganGD_2017.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{HanniganGD_2017.genefamilies_relab.stool}{
#'    An ExpressionSet with 82 samples and 709,894 features specific to the stool body site
#' }
#'
#' \subsection{HanniganGD_2017.marker_abundance.stool}{
#'    An ExpressionSet with 82 samples and 57,511 features specific to the stool body site
#' }
#'
#' \subsection{HanniganGD_2017.marker_presence.stool}{
#'    An ExpressionSet with 82 samples and 52,996 features specific to the stool body site
#' }
#'
#' \subsection{HanniganGD_2017.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 82 samples and 716 features specific to the stool body site
#' }
#'
#' \subsection{HanniganGD_2017.pathabundance_relab.stool}{
#'    An ExpressionSet with 82 samples and 8,500 features specific to the stool body site
#' }
#'
#' \subsection{HanniganGD_2017.pathcoverage.stool}{
#'    An ExpressionSet with 82 samples and 8,500 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples HanniganGD_2017.metaphlan_bugs_list.stool()
#' 
#' @name HanniganGD_2017 
NULL
