## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Marker abundance data from the HMP_2012 dataset
#' 
#' @aliases HMP_2012.marker_abundance.anterior_nares HMP_2012.marker_abundance.buccal_mucosa HMP_2012.marker_abundance.hard_palate HMP_2012.marker_abundance.keratinized_gingiva HMP_2012.marker_abundance.l_retroauricular_crease HMP_2012.marker_abundance.mid_vagina HMP_2012.marker_abundance.palatine_tonsils HMP_2012.marker_abundance.posterior_fornix HMP_2012.marker_abundance.r_retroauricular_crease HMP_2012.marker_abundance.saliva HMP_2012.marker_abundance.stool HMP_2012.marker_abundance.subgingival_plaque HMP_2012.marker_abundance.supragingival_plaque HMP_2012.marker_abundance.throat HMP_2012.marker_abundance.tongue_dorsum HMP_2012.marker_abundance.vaginal_introitus 
#' 
#' @section Datasets: 
#' 
#' \subsection{HMP_2012.marker_abundance.anterior_nares}{
#'    An ExpressionSet with 93 samples and 162,108 features specific to the anterior_nares bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.buccal_mucosa}{
#'    An ExpressionSet with 119 samples and 162,108 features specific to the buccal_mucosa bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.hard_palate}{
#'    An ExpressionSet with 1 sample and 162,108 features specific to the hard_palate bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.keratinized_gingiva}{
#'    An ExpressionSet with 6 samples and 162,108 features specific to the keratinized_gingiva bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.l_retroauricular_crease}{
#'    An ExpressionSet with 9 samples and 162,108 features specific to the l_retroauricular_crease bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.mid_vagina}{
#'    An ExpressionSet with 2 samples and 162,108 features specific to the mid_vagina bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.palatine_tonsils}{
#'    An ExpressionSet with 6 samples and 162,108 features specific to the palatine_tonsils bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.posterior_fornix}{
#'    An ExpressionSet with 62 samples and 162,108 features specific to the posterior_fornix bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.r_retroauricular_crease}{
#'    An ExpressionSet with 18 samples and 162,108 features specific to the r_retroauricular_crease bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.saliva}{
#'    An ExpressionSet with 5 samples and 162,108 features specific to the saliva bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.stool}{
#'    An ExpressionSet with 147 samples and 162,108 features specific to the stool bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.subgingival_plaque}{
#'    An ExpressionSet with 7 samples and 162,108 features specific to the subgingival_plaque bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.supragingival_plaque}{
#'    An ExpressionSet with 128 samples and 162,108 features specific to the supragingival_plaque bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.throat}{
#'    An ExpressionSet with 7 samples and 162,108 features specific to the throat bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.tongue_dorsum}{
#'    An ExpressionSet with 136 samples and 162,108 features specific to the tongue_dorsum bodysite
#' }
#'
#' \subsection{HMP_2012.marker_abundance.vaginal_introitus}{
#'    An ExpressionSet with 3 samples and 162,108 features specific to the vaginal_introitus bodysite
#' }
#' 
#' @source Department of Psychology, Abdul Haq Campus, Federal Urdu University for Arts, Science and Technology, Karachi, Pakistan. shahiq_psy@yahoo.com
#' 
#' @seealso \code{\link{HMP_2012.marker_presence}}, \code{\link{HMP_2012.metaphlan_bugs_list}}, \code{\link{HMP_2012.pathabundance_relab}}, \code{\link{HMP_2012.pathcoverage}}
#' 
#' @examples HMP_2012.marker_abundance.anterior_nares()
#' 
#' @name HMP_2012.marker_abundance 
NULL
