## generated by make_documentation(): do not edit by hand
## see source in inst/scripts/make-documentation.R
#' Marker abundance data from the KarlssonFH_2013 dataset
#'
#' @aliases KarlssonFH_2013.marker_abundance.stool
#'
#' @examples query(ExperimentHub(), "curatedMetagenomicData")
#'
#' @section Datasets:
#'
#' \subsection{KarlssonFH_2013.marker_abundance.stool}{
#'    An ExpressionSet with 145 samples and 101,168 features specific to the stool bodysite
#' }
#'
#' @source Department of Chemical and Biological Engineering, Chalmers University of Technology, SE-412 96 Gothenburg, Sweden.
#'
#' @seealso \code{\link{KarlssonFH_2013.genefamilies_relab}}, \code{\link{KarlssonFH_2013.marker_presence}}, \code{\link{KarlssonFH_2013.metaphlan_bugs_list}}, \code{\link{KarlssonFH_2013.pathabundance_relab}}, \code{\link{KarlssonFH_2013.pathcoverage}}
#'
#' @name KarlssonFH_2013.marker_abundance
NULL
