## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the KarlssonFH_2013 study
#' 
#' @aliases KarlssonFH_2013.genefamilies_relab.stool KarlssonFH_2013.marker_abundance.stool KarlssonFH_2013.marker_presence.stool KarlssonFH_2013.metaphlan_bugs_list.stool KarlssonFH_2013.pathabundance_relab.stool KarlssonFH_2013.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{KarlssonFH_2013.genefamilies_relab.stool}{
#'    An ExpressionSet with 145 samples and 1,415,610 features specific to the stool bodysite
#' }
#'
#' \subsection{KarlssonFH_2013.marker_abundance.stool}{
#'    An ExpressionSet with 145 samples and 101,168 features specific to the stool bodysite
#' }
#'
#' \subsection{KarlssonFH_2013.marker_presence.stool}{
#'    An ExpressionSet with 145 samples and 95,322 features specific to the stool bodysite
#' }
#'
#' \subsection{KarlssonFH_2013.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 145 samples and 1,140 features specific to the stool bodysite
#' }
#'
#' \subsection{KarlssonFH_2013.pathabundance_relab.stool}{
#'    An ExpressionSet with 145 samples and 13,392 features specific to the stool bodysite
#' }
#'
#' \subsection{KarlssonFH_2013.pathcoverage.stool}{
#'    An ExpressionSet with 145 samples and 13,392 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{KarlssonFH_2013_age.png}{options: width="100\%"}}
#' \if{latex}{\figure{KarlssonFH_2013_age.png}}
#'
#'
#' \if{html}{\figure{KarlssonFH_2013_bmi.png}{options: width="100\%"}}
#' \if{latex}{\figure{KarlssonFH_2013_bmi.png}}
#'
#'
#' \if{html}{\figure{KarlssonFH_2013_bodysite.png}{options: width="100\%"}}
#' \if{latex}{\figure{KarlssonFH_2013_bodysite.png}}
#'
#'
#' \if{html}{\figure{KarlssonFH_2013_country.png}{options: width="100\%"}}
#' \if{latex}{\figure{KarlssonFH_2013_country.png}}
#'
#'
#' \if{html}{\figure{KarlssonFH_2013_disease.png}{options: width="100\%"}}
#' \if{latex}{\figure{KarlssonFH_2013_disease.png}}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Gut metagenome in European women with normal, impaired and diabetic glucose control.
#' }
#'
#' \subsection{Author}{
#'    Karlsson FH, Tremaroli V, Nookaew I, Bergström G, Behre CJ, Fagerberg B, Nielsen J, Bäckhed F
#' }
#'
#' \subsection{Lab}{
#'    Department of Chemical and Biological Engineering, Chalmers University of Technology, SE-412 96 Gothenburg, Sweden.
#' }
#'
#' \subsection{PMID}{
#'    23719380
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples KarlssonFH_2013.genefamilies_relab.stool()
#' 
#' @name KarlssonFH_2013 
NULL
