## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Relabeled pathabundance data from the LeChatelierE_2013 dataset
#' 
#' @aliases LeChatelierE_2013.pathabundance_relab.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LeChatelierE_2013.pathabundance_relab.stool}{
#'    An ExpressionSet with 292 samples and 13,504 features specific to the stool bodysite
#' }
#' 
#' @source INRA, Institut National de la Recherche Agronomique, US1367 Metagenopolis, 78350 Jouy en Josas, France.
#' 
#' @seealso \code{\link{LeChatelierE_2013.genefamilies_relab}}, \code{\link{LeChatelierE_2013.marker_abundance}}, \code{\link{LeChatelierE_2013.marker_presence}}, \code{\link{LeChatelierE_2013.metaphlan_bugs_list}}, \code{\link{LeChatelierE_2013.pathcoverage}}
#' 
#' @name LeChatelierE_2013.pathabundance_relab 
NULL
