## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the LeChatelierE_2013 study
#' 
#' @aliases LeChatelierE_2013.genefamilies_relab.stool LeChatelierE_2013.marker_abundance.stool LeChatelierE_2013.marker_presence.stool LeChatelierE_2013.metaphlan_bugs_list.stool LeChatelierE_2013.pathabundance_relab.stool LeChatelierE_2013.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LeChatelierE_2013.genefamilies_relab.stool}{
#'    An ExpressionSet with 292 samples and 1,519,376 features specific to the stool bodysite
#' }
#'
#' \subsection{LeChatelierE_2013.marker_abundance.stool}{
#'    An ExpressionSet with 292 samples and 130,621 features specific to the stool bodysite
#' }
#'
#' \subsection{LeChatelierE_2013.marker_presence.stool}{
#'    An ExpressionSet with 292 samples and 117,258 features specific to the stool bodysite
#' }
#'
#' \subsection{LeChatelierE_2013.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 292 samples and 1,542 features specific to the stool bodysite
#' }
#'
#' \subsection{LeChatelierE_2013.pathabundance_relab.stool}{
#'    An ExpressionSet with 292 samples and 13,504 features specific to the stool bodysite
#' }
#'
#' \subsection{LeChatelierE_2013.pathcoverage.stool}{
#'    An ExpressionSet with 292 samples and 13,504 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{LeChatelierE_2013_bmi.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{LeChatelierE_2013_bodysite.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{LeChatelierE_2013_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{LeChatelierE_2013_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Richness of human gut microbiome correlates with metabolic markers.
#' }
#'
#' \subsection{Author}{
#'    Le Chatelier E, Nielsen T, Qin J, Prifti E, Hildebrand F, Falony G, Almeida M, Arumugam M, Batto JM, Kennedy S, Leonard P, Li J, Burgdorf K, Grarup N, Jørgensen T, Brandslund I, Nielsen HB, Juncker AS, Bertalan M, Levenez F, Pons N, Rasmussen S, Sunagawa S, Tap J, Tims S, Zoetendal EG, Brunak S, Clément K, Doré J, Kleerebezem M, Kristiansen K, Renault P, Sicheritz-Ponten T, de Vos WM, Zucker JD, Raes J, Hansen T, Bork P, Wang J, Ehrlich SD, Pedersen O, Guedon E, Delorme C, Layec S, Khaci G, van de Guchte M, Vandemeulebrouck G, Jamet A, Dervyn R, Sanchez N, Maguin E, Haimet F, Winogradski Y, Cultrone A, Leclerc M, Juste C, Blottière H, Pelletier E, LePaslier D, Artiguenave F, Bruls T, Weissenbach J, Turner K, Parkhill J, Antolin M, Manichanh C, Casellas F, Boruel N, Varela E, Torrejon A, Guarner F, Denariaz G, Derrien M, van Hylckama Vlieg JE, Veiga P, Oozeer R, Knol J, Rescigno M, Brechot C, M'Rini C, Mérieux A, Yamada T
#' }
#'
#' \subsection{Lab}{
#'    INRA, Institut National de la Recherche Agronomique, US1367 Metagenopolis, 78350 Jouy en Josas, France.
#' }
#'
#' \subsection{PMID}{
#'    23985870
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples LeChatelierE_2013.genefamilies_relab.stool()
#' 
#' @name LeChatelierE_2013 
NULL
