## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the LiuW_2016 study
#' 
#' @aliases 20170526.LiuW_2016.genefamilies_relab.stool 20170526.LiuW_2016.marker_abundance.stool 20170526.LiuW_2016.marker_presence.stool 20170526.LiuW_2016.metaphlan_bugs_list.stool 20170526.LiuW_2016.pathabundance_relab.stool 20170526.LiuW_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{20170526.LiuW_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 110 samples and 1,178,616 features specific to the stool body site
#' }
#'
#' \subsection{20170526.LiuW_2016.marker_abundance.stool}{
#'    An ExpressionSet with 110 samples and 81,028 features specific to the stool body site
#' }
#'
#' \subsection{20170526.LiuW_2016.marker_presence.stool}{
#'    An ExpressionSet with 110 samples and 76,593 features specific to the stool body site
#' }
#'
#' \subsection{20170526.LiuW_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 110 samples and 1,078 features specific to the stool body site
#' }
#'
#' \subsection{20170526.LiuW_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 110 samples and 12,647 features specific to the stool body site
#' }
#'
#' \subsection{20170526.LiuW_2016.pathcoverage.stool}{
#'    An ExpressionSet with 110 samples and 12,647 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{LiuW_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{LiuW_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Unique Features of Ethnic Mongolian Gut Microbiome revealed by metagenomic analysis.
#' }
#'
#' \subsection{Author}{
#'    Liu W, Zhang J, Wu C, Cai S, Huang W, Chen J, Xi X, Liang Z, Hou Q, Zhou B, Qin N, Zhang H
#' }
#'
#' \subsection{Lab}{
#'    Key Laboratory of Dairy Biotechnology and Engineering, Education Ministry of P. R. China, Department of Food Science and Engineering, Inner Mongolia Agricultural University, Hohhot 010018, China.
#' }
#'
#' \subsection{PMID}{
#'    27708392
#' }
#' 
#' @examples 20170526.LiuW_2016.genefamilies_relab.stool()
#' 
#' @name LiuW_2016 
NULL
 