## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the LomanNJ_2013_Mi study
#' 
#' @aliases LomanNJ_2013_Mi.genefamilies_relab.stool LomanNJ_2013_Mi.marker_abundance.stool LomanNJ_2013_Mi.marker_presence.stool LomanNJ_2013_Mi.metaphlan_bugs_list.stool LomanNJ_2013_Mi.pathabundance_relab.stool LomanNJ_2013_Mi.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LomanNJ_2013_Mi.genefamilies_relab.stool}{
#'    An ExpressionSet with 9 samples and 337,637 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Mi.marker_abundance.stool}{
#'    An ExpressionSet with 9 samples and 24,228 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Mi.marker_presence.stool}{
#'    An ExpressionSet with 9 samples and 22,710 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Mi.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 9 samples and 399 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Mi.pathabundance_relab.stool}{
#'    An ExpressionSet with 9 samples and 4,606 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Mi.pathcoverage.stool}{
#'    An ExpressionSet with 9 samples and 4,606 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' LomanNJ_2013_Mi.bodysite.pdf
#' \if{html}\figure{LomanNJ_2013_Mi.bodysite.png}{options: width="100\%"}
#' \if{latex}\figure{LomanNJ_2013_Mi.bodysite.pdf}
#'
#'LomanNJ_2013_Mi.bodysite.png
#' \if{html}\figure{LomanNJ_2013_Mi.bodysite.png}{options: width="100\%"}
#' \if{latex}\figure{LomanNJ_2013_Mi.bodysite.pdf}
#'
#'LomanNJ_2013_Mi.country.pdf
#' \if{html}\figure{LomanNJ_2013_Mi.bodysite.png}{options: width="100\%"}
#' \if{latex}\figure{LomanNJ_2013_Mi.bodysite.pdf}
#'
#'LomanNJ_2013_Mi.country.png
#' \if{html}\figure{LomanNJ_2013_Mi.bodysite.png}{options: width="100\%"}
#' \if{latex}\figure{LomanNJ_2013_Mi.bodysite.pdf}
#'
#'LomanNJ_2013_Mi.disease.pdf
#' \if{html}\figure{LomanNJ_2013_Mi.bodysite.png}{options: width="100\%"}
#' \if{latex}\figure{LomanNJ_2013_Mi.bodysite.pdf}
#'
#'LomanNJ_2013_Mi.disease.png
#' \if{html}\figure{LomanNJ_2013_Mi.bodysite.png}{options: width="100\%"}
#' \if{latex}\figure{LomanNJ_2013_Mi.bodysite.pdf}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    A culture-independent sequence-based metagenomics approach to the investigation of an outbreak of Shiga-toxigenic Escherichia coli O104:H4.
#' }
#'
#' \subsection{Author}{
#'    Loman NJ, Constantinidou C, Christner M, Rohde H, Chan JZ, Quick J, Weir JC, Quince C, Smith GP, Betley JR, Aepfelbacher M, Pallen MJ
#' }
#'
#' \subsection{Lab}{
#'    Institute of Microbiology and Infection, University of Birmingham, Birmingham, England.
#' }
#'
#' \subsection{PMID}{
#'    23571589
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples LomanNJ_2013_Mi.genefamilies_relab.stool()
#' 
#' @name LomanNJ_2013_Mi 
NULL
