## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the LomanNJ_2013 study
#' 
#' @aliases LomanNJ_2013.genefamilies_relab.stool LomanNJ_2013.marker_abundance.stool LomanNJ_2013.marker_presence.stool LomanNJ_2013.metaphlan_bugs_list.stool LomanNJ_2013.pathabundance_relab.stool LomanNJ_2013.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LomanNJ_2013.genefamilies_relab.stool}{
#'    An ExpressionSet with 43 samples and 716,332 features specific to the stool body site
#' }
#'
#' \subsection{LomanNJ_2013.marker_abundance.stool}{
#'    An ExpressionSet with 43 samples and 56,517 features specific to the stool body site
#' }
#'
#' \subsection{LomanNJ_2013.marker_presence.stool}{
#'    An ExpressionSet with 43 samples and 53,285 features specific to the stool body site
#' }
#'
#' \subsection{LomanNJ_2013.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 43 samples and 736 features specific to the stool body site
#' }
#'
#' \subsection{LomanNJ_2013.pathabundance_relab.stool}{
#'    An ExpressionSet with 43 samples and 8,657 features specific to the stool body site
#' }
#'
#' \subsection{LomanNJ_2013.pathcoverage.stool}{
#'    An ExpressionSet with 43 samples and 8,657 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    A culture-independent sequence-based metagenomics approach to the investigation of an outbreak of Shiga-toxigenic Escherichia coli O104:H4.
#' }
#'
#' \subsection{Author}{
#'    Loman NJ, Constantinidou C, Christner M, Rohde H, Chan JZ, Quick J, Weir JC, Quince C, Smith GP, Betley JR, Aepfelbacher M, Pallen MJ
#' }
#'
#' \subsection{Lab}{
#'    [1] Institute of Microbiology and Infection, University of Birmingham, Birmingham, England.
#' }
#'
#' \subsection{PMID}{
#'    23571589
#' }
#' 
#' @examples LomanNJ_2013.metaphlan_bugs_list.stool()
#' 
#' @name LomanNJ_2013 
NULL
