## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Taxonomic abundance data from the LomanNJ_2013_Hi dataset
#' 
#' @aliases LomanNJ_2013_Hi.metaphlan_bugs_list.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LomanNJ_2013_Hi.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 44 samples and 736 features specific to the stool bodysite
#' }
#' 
#' @source Institute of Microbiology and Infection, University of Birmingham, Birmingham, England.
#' 
#' @seealso \code{\link{LomanNJ_2013_Hi.genefamilies_relab}}, \code{\link{LomanNJ_2013_Hi.marker_abundance}}, \code{\link{LomanNJ_2013_Hi.marker_presence}}, \code{\link{LomanNJ_2013_Hi.pathabundance_relab}}, \code{\link{LomanNJ_2013_Hi.pathcoverage}}
#' 
#' @name LomanNJ_2013_Hi.metaphlan_bugs_list 
NULL
