## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Pathcoverage data from the LomanNJ_2013_Mi dataset
#' 
#' @aliases LomanNJ_2013_Mi.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LomanNJ_2013_Mi.pathcoverage.stool}{
#'    An ExpressionSet with 9 samples and 4,606 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \figure{LomanNJ_2013_Mi.bodysite.png}{options: width="100\%"}
#'
#' \figure{LomanNJ_2013_Mi.country.png}{options: width="100\%"}
#'
#' \figure{LomanNJ_2013_Mi.disease.png}{options: width="100\%"}
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    A culture-independent sequence-based metagenomics approach to the investigation of an outbreak of Shiga-toxigenic Escherichia coli O104:H4.
#' }
#'
#' \subsection{Author}{
#'    Loman NJ, Constantinidou C, Christner M, Rohde H, Chan JZ, Quick J, Weir JC, Quince C, Smith GP, Betley JR, Aepfelbacher M, Pallen MJ
#' }
#'
#' \subsection{Lab}{
#'    Institute of Microbiology and Infection, University of Birmingham, Birmingham, England.
#' }
#'
#' \subsection{PMID}{
#'    23571589
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples LomanNJ_2013_Mi.pathcoverage.stool()
#' 
#' @name LomanNJ_2013_Mi.pathcoverage 
NULL
