## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the LomanNJ_2013_Hi study
#' 
#' @aliases LomanNJ_2013_Hi.genefamilies_relab.stool LomanNJ_2013_Hi.marker_abundance.stool LomanNJ_2013_Hi.marker_presence.stool LomanNJ_2013_Hi.metaphlan_bugs_list.stool LomanNJ_2013_Hi.pathabundance_relab.stool LomanNJ_2013_Hi.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LomanNJ_2013_Hi.genefamilies_relab.stool}{
#'    An ExpressionSet with 44 samples and 718,320 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Hi.marker_abundance.stool}{
#'    An ExpressionSet with 44 samples and 56,689 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Hi.marker_presence.stool}{
#'    An ExpressionSet with 44 samples and 53,443 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Hi.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 44 samples and 736 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Hi.pathabundance_relab.stool}{
#'    An ExpressionSet with 44 samples and 8,716 features specific to the stool bodysite
#' }
#'
#' \subsection{LomanNJ_2013_Hi.pathcoverage.stool}{
#'    An ExpressionSet with 44 samples and 8,716 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \figure{LomanNJ_2013_Hi.bodysite.png}{options: width="100\%"}
#'
#' \figure{LomanNJ_2013_Hi.country.png}{options: width="100\%"}
#'
#' \figure{LomanNJ_2013_Hi.disease.png}{options: width="100\%"}
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    A culture-independent sequence-based metagenomics approach to the investigation of an outbreak of Shiga-toxigenic Escherichia coli O104:H4.
#' }
#'
#' \subsection{Author}{
#'    Loman NJ, Constantinidou C, Christner M, Rohde H, Chan JZ, Quick J, Weir JC, Quince C, Smith GP, Betley JR, Aepfelbacher M, Pallen MJ
#' }
#'
#' \subsection{Lab}{
#'    Institute of Microbiology and Infection, University of Birmingham, Birmingham, England.
#' }
#'
#' \subsection{PMID}{
#'    23571589
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples LomanNJ_2013_Hi.genefamilies_relab.stool()
#' 
#' @name LomanNJ_2013_Hi 
NULL
