## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Pathcoverage data from the LomanNJ_2013_Mi dataset
#' 
#' @aliases LomanNJ_2013_Mi.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{LomanNJ_2013_Mi.pathcoverage.stool}{
#'    An ExpressionSet with 9 samples and 4,606 features specific to the stool bodysite
#' }
#' 
#' @source Institute of Microbiology and Infection, University of Birmingham, Birmingham, England.
#' 
#' @seealso \code{\link{LomanNJ_2013_Mi.genefamilies_relab}}, \code{\link{LomanNJ_2013_Mi.marker_abundance}}, \code{\link{LomanNJ_2013_Mi.marker_presence}}, \code{\link{LomanNJ_2013_Mi.metaphlan_bugs_list}}, \code{\link{LomanNJ_2013_Mi.pathabundance_relab}}
#' 
#' @name LomanNJ_2013_Mi.pathcoverage 
NULL
