## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the MatsonV_2018 study
#' 
#' @aliases MatsonV_2018.genefamilies_relab.stool MatsonV_2018.marker_abundance.stool MatsonV_2018.marker_presence.stool MatsonV_2018.metaphlan_bugs_list.stool MatsonV_2018.pathabundance_relab.stool MatsonV_2018.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{MatsonV_2018.genefamilies_relab.stool}{
#'    An ExpressionSet with 39 samples and 1,198,303 features specific to the stool body site
#' }
#'
#' \subsection{MatsonV_2018.marker_abundance.stool}{
#'    An ExpressionSet with 39 samples and 75,666 features specific to the stool body site
#' }
#'
#' \subsection{MatsonV_2018.marker_presence.stool}{
#'    An ExpressionSet with 39 samples and 73,435 features specific to the stool body site
#' }
#'
#' \subsection{MatsonV_2018.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 39 samples and 921 features specific to the stool body site
#' }
#'
#' \subsection{MatsonV_2018.pathabundance_relab.stool}{
#'    An ExpressionSet with 39 samples and 7,058 features specific to the stool body site
#' }
#'
#' \subsection{MatsonV_2018.pathcoverage.stool}{
#'    An ExpressionSet with 39 samples and 7,058 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    The commensal microbiome is associated with anti-PD-1 efficacy in metastatic melanoma patients.
#' }
#'
#' \subsection{Author}{
#'    Matson V, Fessler J, Bao R, Chongsuwat T, Zha Y, Alegre ML, Luke JJ, Gajewski TF
#' }
#'
#' \subsection{Lab}{
#'    [1] Department of Pathology, University of Chicago, Chicago, IL 60637, USA., [2] Center for Research Informatics, University of Chicago, IL 60637, USA., [3] Department of Pediatrics, University of Chicago, IL 60637, USA., [4] Department of Medicine, University of Chicago, Chicago, IL 60637, USA.
#' }
#'
#' \subsection{PMID}{
#'    29302014
#' }
#' 
#' @examples MatsonV_2018.metaphlan_bugs_list.stool()
#' 
#' @name MatsonV_2018 
NULL
