## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the NielsenHB_2014 study
#' 
#' @aliases 20170526.NielsenHB_2014.genefamilies_relab.stool 20170526.NielsenHB_2014.marker_abundance.stool 20170526.NielsenHB_2014.marker_presence.stool 20170526.NielsenHB_2014.metaphlan_bugs_list.stool 20170526.NielsenHB_2014.pathabundance_relab.stool 20170526.NielsenHB_2014.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{20170526.NielsenHB_2014.genefamilies_relab.stool}{
#'    An ExpressionSet with 396 samples and 1,730,383 features specific to the stool body site
#' }
#'
#' \subsection{20170526.NielsenHB_2014.marker_abundance.stool}{
#'    An ExpressionSet with 396 samples and 222,837 features specific to the stool body site
#' }
#'
#' \subsection{20170526.NielsenHB_2014.marker_presence.stool}{
#'    An ExpressionSet with 396 samples and 188,446 features specific to the stool body site
#' }
#'
#' \subsection{20170526.NielsenHB_2014.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 396 samples and 1,939 features specific to the stool body site
#' }
#'
#' \subsection{20170526.NielsenHB_2014.pathabundance_relab.stool}{
#'    An ExpressionSet with 396 samples and 17,280 features specific to the stool body site
#' }
#'
#' \subsection{20170526.NielsenHB_2014.pathcoverage.stool}{
#'    An ExpressionSet with 396 samples and 17,280 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{NielsenHB_2014_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{NielsenHB_2014_BMI.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{NielsenHB_2014_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{NielsenHB_2014_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{NielsenHB_2014_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Identification and assembly of genomes and genetic elements in complex metagenomic samples without using reference genomes.
#' }
#'
#' \subsection{Author}{
#'    Nielsen HB, Almeida M, Juncker AS, Rasmussen S, Li J, Sunagawa S, Plichta DR, Gautier L, Pedersen AG, Le Chatelier E, Pelletier E, Bonde I, Nielsen T, Manichanh C, Arumugam M, Batto JM, Quintanilha Dos Santos MB, Blom N, Borruel N, Burgdorf KS, Boumezbeur F, Casellas F, Doré J, Dworzynski P, Guarner F, Hansen T, Hildebrand F, Kaas RS, Kennedy S, Kristiansen K, Kultima JR, Léonard P, Levenez F, Lund O, Moumen B, Le Paslier D, Pons N, Pedersen O, Prifti E, Qin J, Raes J, Sørensen S, Tap J, Tims S, Ussery DW, Yamada T, Renault P, Sicheritz-Ponten T, Bork P, Wang J, Brunak S, Ehrlich SD, Nielsen HB, Almeida M, Juncker AS, Rasmussen S, Li J, Sunagawa S, Plichta DR, Gautier L, Pedersen AG, Le Chatelier E, Pelletier E, Bonde I, Nielsen T, Manichanh C, Arumugam M, Batto JM, Quintanilha Dos Santos MB, Blom N, Borruel N, Burgdorf KS, Boumezbeur F, Casellas F, Doré J, Dworzynski P, Guarner F, Hansen T, Hildebrand F, Kaas RS, Kennedy S, Kristiansen K, Kultima JR, Leonard P, Levenez F, Lund O, Moumen B, Le Paslier D, Pons N, Pedersen O, Prifti E, Qin J, Raes J, Sørensen S, Tap J, Tims S, Ussery DW, Yamada T, Renault P, Sicheritz-Ponten T, Bork P, Wang J, Brunak S, Ehrlich SD, Jamet A, Mérieux A, Cultrone A, Torrejon A, Quinquis B, Brechot C, Delorme C, M'Rini C, de Vos WM, Maguin E, Varela E, Guedon E, Gwen F, Haimet F, Artiguenave F, Vandemeulebrouck G, Denariaz G, Khaci G, Blottière H, Knol J, Weissenbach J, van Hylckama Vlieg JE, Torben J, Parkhill J, Turner K, van de Guchte M, Antolin M, Rescigno M, Kleerebezem M, Derrien M, Galleron N, Sanchez N, Grarup N, Veiga P, Oozeer R, Dervyn R, Layec S, Bruls T, Winogradski Y, Erwin G Z
#' }
#'
#' \subsection{Lab}{
#'    [1] Center for Biological Sequence Analysis, Technical University of Denmark, Kongens Lyngby, Denmark. [2] Novo Nordisk Foundation Center for Biosustainability, Technical University of Denmark, Kongens Lyngby, Denmark. [3].
#' }
#'
#' \subsection{PMID}{
#'    24997787
#' }
#' 
#' @examples 20170526.NielsenHB_2014.genefamilies_relab.stool()
#' 
#' @name NielsenHB_2014 
NULL
 