## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Taxonomic abundance data from the NielsenHB_2014 dataset
#' 
#' @aliases NielsenHB_2014.metaphlan_bugs_list.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{NielsenHB_2014.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 396 samples and 1,939 features specific to the stool bodysite
#' }
#' 
#' @source 1] Center for Biological Sequence Analysis, Technical University of Denmark, Kongens Lyngby, Denmark. [2] Novo Nordisk Foundation Center for Biosustainability, Technical University of Denmark, Kongens Lyngby, Denmark. [3].
#' 
#' @seealso \code{\link{NielsenHB_2014.genefamilies_relab}}, \code{\link{NielsenHB_2014.marker_abundance}}, \code{\link{NielsenHB_2014.marker_presence}}, \code{\link{NielsenHB_2014.pathabundance_relab}}, \code{\link{NielsenHB_2014.pathcoverage}}
#' 
#' @name NielsenHB_2014.metaphlan_bugs_list 
NULL
