## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Pathcoverage data from the Obregon_TitoAJ_2015 dataset
#' 
#' @aliases Obregon_TitoAJ_2015.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{Obregon_TitoAJ_2015.pathcoverage.stool}{
#'    An ExpressionSet with 58 samples and 10,438 features specific to the stool bodysite
#' }
#' 
#' @source [1] Department of Anthropology, University of Oklahoma, Dale Hall Tower, 521 Norman, Oklahoma 73019, USA [2] Universidad Cientifica del Sur, Lima 18, Peru [3] City of Hope, NCI-designated Comprehensive Cancer Center, Duarte, California 91010, USA.
#' 
#' @seealso \code{\link{Obregon_TitoAJ_2015.genefamilies_relab}}, \code{\link{Obregon_TitoAJ_2015.marker_abundance}}, \code{\link{Obregon_TitoAJ_2015.marker_presence}}, \code{\link{Obregon_TitoAJ_2015.metaphlan_bugs_list}}, \code{\link{Obregon_TitoAJ_2015.pathabundance_relab}}
#' 
#' @examples Obregon_TitoAJ_2015.pathcoverage.stool()
#' 
#' @name Obregon_TitoAJ_2015.pathcoverage 
NULL
