## generated by make_data_documentation(): do not edit by hand
## see source in data-raw/make_data_documentation.R
#' Data from the Obregon-TitoAJ_2015 study
#'
#' @aliases Obregon-TitoAJ_2015.genefamilies_relab.stool Obregon-TitoAJ_2015.marker_abundance.stool Obregon-TitoAJ_2015.marker_presence.stool Obregon-TitoAJ_2015.metaphlan_bugs_list.stool Obregon-TitoAJ_2015.pathabundance_relab.stool Obregon-TitoAJ_2015.pathcoverage.stool Obregon_TitoAJ_2015 Obregon_TitoAJ_2015.genefamilies_relab.stool Obregon_TitoAJ_2015.marker_abundance.stool Obregon_TitoAJ_2015.marker_presence.stool Obregon_TitoAJ_2015.metaphlan_bugs_list.stool Obregon_TitoAJ_2015.pathabundance_relab.stool Obregon_TitoAJ_2015.pathcoverage.stool
#' @details Note that Obregon_TitoAJ_2015 is deprecated, use Obregon-TitoAJ_2015 instead.
#'
#' @section Datasets:
#'
#' \subsection{Obregon-TitoAJ_2015.genefamilies_relab.stool}{
#'    An ExpressionSet with 58 samples and 1,185,621 features specific to the stool body site
#' }
#'
#' \subsection{Obregon-TitoAJ_2015.marker_abundance.stool}{
#'    An ExpressionSet with 58 samples and 96,336 features specific to the stool body site
#' }
#'
#' \subsection{Obregon-TitoAJ_2015.marker_presence.stool}{
#'    An ExpressionSet with 58 samples and 86,352 features specific to the stool body site
#' }
#'
#' \subsection{Obregon-TitoAJ_2015.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 58 samples and 1,094 features specific to the stool body site
#' }
#'
#' \subsection{Obregon-TitoAJ_2015.pathabundance_relab.stool}{
#'    An ExpressionSet with 58 samples and 9,801 features specific to the stool body site
#' }
#'
#' \subsection{Obregon-TitoAJ_2015.pathcoverage.stool}{
#'    An ExpressionSet with 58 samples and 9,801 features specific to the stool body site
#' }
#'
#' @section Source:
#'
#' \subsection{Title}{
#'    Subsistence strategies in traditional societies distinguish gut microbiomes.
#' }
#'
#' \subsection{Author}{
#'    Obregon-Tito AJ, Tito RY, Metcalf J, Sankaranarayanan K, Clemente JC, Ursell LK, Zech Xu Z, Van Treuren W, Knight R, Gaffney PM, Spicer P, Lawson P, Marin-Reyes L, Trujillo-Villarroel O, Foster M, Guija-Poma E, Troncoso-Corzo L, Warinner C, Ozga AT, Lewis CM
#' }
#'
#' \subsection{Lab}{
#'    [1] 1] Department of Anthropology, University of Oklahoma, Dale Hall Tower, 521 Norman, Oklahoma 73019, USA [2] Universidad Cientifica del Sur, Lima 18, Peru [3] City of Hope, NCI-designated Comprehensive Cancer Center, Duarte, California 91010, USA., [2] 1] Department of Anthropology, University of Oklahoma, Dale Hall Tower, 521 Norman, Oklahoma 73019, USA [2] Universidad Cientifica del Sur, Lima 18, Peru, [3] City of Hope, NCI-designated Comprehensive Cancer Center, Duarte, California 91010, USA., [4] Department of Anthropology, University of Oklahoma, Dale Hall Tower, 521 Norman, Oklahoma 73019, USA., [5] Department of Chemistry and Biochemistry, University of Colorado, Boulder, Colorado 80309, USA., [6] Departments of Pediatrics and Computer Science &amp;Engineering University of California San Diego, La Jolla, CA 92093, USA., [7] Oklahoma Medical Research Foundation, Oklahoma City, Oklahoma 73104, USA., [8] Instituto Nacional de Salud, Lima 11, Peru, [9] Old Dominion University, Norfolk, Virginia 23529, USA., [10] Universidad Cientifica del Sur, Lima 18, Peru
#' }
#'
#' \subsection{PMID}{
#'    25807110
#' }
#'
#' @examples `Obregon-TitoAJ_2015.metaphlan_bugs_list.stool`()
#'
#' @name Obregon-TitoAJ_2015
NULL
