## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the Obregon_TitoAJ_2015 study
#' 
#' @aliases Obregon_TitoAJ_2015.genefamilies_relab.stool Obregon_TitoAJ_2015.marker_abundance.stool Obregon_TitoAJ_2015.marker_presence.stool Obregon_TitoAJ_2015.metaphlan_bugs_list.stool Obregon_TitoAJ_2015.pathabundance_relab.stool Obregon_TitoAJ_2015.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{Obregon_TitoAJ_2015.genefamilies_relab.stool}{
#'    An ExpressionSet with 58 samples and 1,192,382 features specific to the stool bodysite
#' }
#'
#' \subsection{Obregon_TitoAJ_2015.marker_abundance.stool}{
#'    An ExpressionSet with 58 samples and 195,320 features specific to the stool bodysite
#' }
#'
#' \subsection{Obregon_TitoAJ_2015.marker_presence.stool}{
#'    An ExpressionSet with 58 samples and 150,347 features specific to the stool bodysite
#' }
#'
#' \subsection{Obregon_TitoAJ_2015.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 58 samples and 1,548 features specific to the stool bodysite
#' }
#'
#' \subsection{Obregon_TitoAJ_2015.pathabundance_relab.stool}{
#'    An ExpressionSet with 58 samples and 10,438 features specific to the stool bodysite
#' }
#'
#' \subsection{Obregon_TitoAJ_2015.pathcoverage.stool}{
#'    An ExpressionSet with 58 samples and 10,438 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{Obregon_TitoAJ_2015_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{Obregon_TitoAJ_2015_bmi.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{Obregon_TitoAJ_2015_bodysite.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{Obregon_TitoAJ_2015_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{Obregon_TitoAJ_2015_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{Obregon_TitoAJ_2015_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Subsistence strategies in traditional societies distinguish gut microbiomes.
#' }
#'
#' \subsection{Author}{
#'    Obregon-Tito AJ, Tito RY, Metcalf J, Sankaranarayanan K, Clemente JC, Ursell LK, Zech Xu Z, Van Treuren W, Knight R, Gaffney PM, Spicer P, Lawson P, Marin-Reyes L, Trujillo-Villarroel O, Foster M, Guija-Poma E, Troncoso-Corzo L, Warinner C, Ozga AT, Lewis CM
#' }
#'
#' \subsection{Lab}{
#'    [1] Department of Anthropology, University of Oklahoma, Dale Hall Tower, 521 Norman, Oklahoma 73019, USA [2] Universidad Cientifica del Sur, Lima 18, Peru [3] City of Hope, NCI-designated Comprehensive Cancer Center, Duarte, California 91010, USA.
#' }
#'
#' \subsection{PMID}{
#'    25807110
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples Obregon_TitoAJ_2015.genefamilies_relab.stool()
#' 
#' @name Obregon_TitoAJ_2015 
NULL
