## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Relabeled genefamilies data from the Obregon-TitoAJ_2015 dataset
#' 
#' @aliases Obregon-TitoAJ_2015.genefamilies_relab.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{Obregon-TitoAJ_2015.genefamilies_relab.stool}{
#'    An ExpressionSet with 58 samples and 1,192,382 features specific to the stool bodysite
#' }
#' 
#' @source 1] Department of Anthropology, University of Oklahoma, Dale Hall Tower, 521 Norman, Oklahoma 73019, USA [2] Universidad Científica del Sur, Lima 18, Perú [3] City of Hope, NCI-designated Comprehensive Cancer Center, Duarte, California 91010, USA.
#' 
#' @seealso \code{\link{Obregon-TitoAJ_2015.marker_abundance}}, \code{\link{Obregon-TitoAJ_2015.marker_presence}}, \code{\link{Obregon-TitoAJ_2015.metaphlan_bugs_list}}, \code{\link{Obregon-TitoAJ_2015.pathabundance_relab}}, \code{\link{Obregon-TitoAJ_2015.pathcoverage}}
#' 
#' @examples Obregon-TitoAJ_2015.genefamilies_relab.stool()
#' 
#' @name Obregon-TitoAJ_2015.genefamilies_relab 
NULL
