## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the OhJ_2014 study
#' 
#' @aliases OhJ_2014.genefamilies_relab.skin OhJ_2014.marker_abundance.skin OhJ_2014.marker_presence.skin OhJ_2014.metaphlan_bugs_list.skin OhJ_2014.pathabundance_relab.skin OhJ_2014.pathcoverage.skin 
#' 
#' @section Datasets: 
#' 
#' \subsection{OhJ_2014.genefamilies_relab.skin}{
#'    An ExpressionSet with 291 samples and 3,956,472 features specific to the skin body site
#' }
#'
#' \subsection{OhJ_2014.marker_abundance.skin}{
#'    An ExpressionSet with 291 samples and 202,657 features specific to the skin body site
#' }
#'
#' \subsection{OhJ_2014.marker_presence.skin}{
#'    An ExpressionSet with 291 samples and 184,914 features specific to the skin body site
#' }
#'
#' \subsection{OhJ_2014.metaphlan_bugs_list.skin}{
#'    An ExpressionSet with 291 samples and 2,461 features specific to the skin body site
#' }
#'
#' \subsection{OhJ_2014.pathabundance_relab.skin}{
#'    An ExpressionSet with 291 samples and 48,536 features specific to the skin body site
#' }
#'
#' \subsection{OhJ_2014.pathcoverage.skin}{
#'    An ExpressionSet with 291 samples and 48,536 features specific to the skin body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Biogeography and individuality shape function in the human skin metagenome.
#' }
#'
#' \subsection{Author}{
#'    Oh J, Byrd AL, Deming C, Conlan S, Kong HH, Segre JA, Barnabas B, Blakesley R, Bouffard G, Brooks S, Coleman H, Dekhtyar M, Gregory M, Guan X, Gupta J, Han J, Ho SL, Legaspi R, Maduro Q, Masiello C, Maskeri B, McDowell J, Montemayor C, Mullikin J, Park M, Riebow N, Schandler K, Schmidt B, Sison C, Stantripop M, Thomas J, Thomas P, Vemulapalli M, Young A
#' }
#'
#' \subsection{Lab}{
#'    [1] Translational and Functional Genomics Branch, National Human Genome Research Institute, NIH, Bethesda, Maryland 20892, USA., [2] 1] Dermatology Branch, Center for Cancer Research, National Cancer Institute, NIH, Bethesda, Maryland 20892, USA [2]., [3] 1] Translational and Functional Genomics Branch, National Human Genome Research Institute, NIH, Bethesda, Maryland 20892, USA [2].
#' }
#'
#' \subsection{PMID}{
#'    25279917
#' }
#' 
#' @examples OhJ_2014.metaphlan_bugs_list.skin()
#' 
#' @name OhJ_2014 
NULL
