## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Pathcoverage data from the OhJ_2014 dataset
#' 
#' @aliases OhJ_2014.pathcoverage.skin 
#' 
#' @section Datasets: 
#' 
#' \subsection{OhJ_2014.pathcoverage.skin}{
#'    An ExpressionSet with 291 samples and 48,536 features specific to the skin bodysite
#' }
#' 
#' @source Translational and Functional Genomics Branch, National Human Genome Research Institute, NIH, Bethesda, Maryland 20892, USA.
#' 
#' @seealso \code{\link{OhJ_2014.genefamilies_relab}}, \code{\link{OhJ_2014.marker_abundance}}, \code{\link{OhJ_2014.marker_presence}}, \code{\link{OhJ_2014.metaphlan_bugs_list}}, \code{\link{OhJ_2014.pathabundance_relab}}
#' 
#' @examples OhJ_2014.pathcoverage.skin()
#' 
#' @name OhJ_2014.pathcoverage 
NULL
