## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Relabeled genefamilies data from the OhJ_2014 dataset
#' 
#' @aliases OhJ_2014.genefamilies_relab.skin 
#' 
#' @section Datasets: 
#' 
#' \subsection{OhJ_2014.genefamilies_relab.skin}{
#'    An ExpressionSet with 291 samples and 3,956,473 features specific to the skin bodysite
#' }
#' 
#' @source Translational and Functional Genomics Branch, National Human Genome Research Institute, NIH, Bethesda, Maryland 20892, USA., Pharmacy Department, Yale-New Haven Hospital, New Haven, Connecticut.
#' 
#' @seealso \code{\link{OhJ_2014.marker_abundance}}, \code{\link{OhJ_2014.marker_presence}}, \code{\link{OhJ_2014.metaphlan_bugs_list}}, \code{\link{OhJ_2014.pathabundance_relab}}, \code{\link{OhJ_2014.pathcoverage}}
#' 
#' @name OhJ_2014.genefamilies_relab 
NULL
