## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the PasolliE_2018 study
#' 
#' @aliases PasolliE_2018.genefamilies_relab.stool PasolliE_2018.marker_abundance.stool PasolliE_2018.marker_presence.stool PasolliE_2018.metaphlan_bugs_list.stool PasolliE_2018.pathabundance_relab.stool PasolliE_2018.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{PasolliE_2018.genefamilies_relab.stool}{
#'    An ExpressionSet with 112 samples and 1,242,950 features specific to the stool body site
#' }
#'
#' \subsection{PasolliE_2018.marker_abundance.stool}{
#'    An ExpressionSet with 112 samples and 87,770 features specific to the stool body site
#' }
#'
#' \subsection{PasolliE_2018.marker_presence.stool}{
#'    An ExpressionSet with 112 samples and 82,466 features specific to the stool body site
#' }
#'
#' \subsection{PasolliE_2018.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 112 samples and 1,111 features specific to the stool body site
#' }
#'
#' \subsection{PasolliE_2018.pathabundance_relab.stool}{
#'    An ExpressionSet with 112 samples and 13,695 features specific to the stool body site
#' }
#'
#' \subsection{PasolliE_2018.pathcoverage.stool}{
#'    An ExpressionSet with 112 samples and 13,695 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples `PasolliE_2018.metaphlan_bugs_list.stool`()
#' 
#' @name PasolliE_2018 
NULL
