## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the QinJ_2012 study
#' 
#' @aliases QinJ_2012.genefamilies_relab.stool QinJ_2012.marker_abundance.stool QinJ_2012.marker_presence.stool QinJ_2012.metaphlan_bugs_list.stool QinJ_2012.pathabundance_relab.stool QinJ_2012.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{QinJ_2012.genefamilies_relab.stool}{
#'    An ExpressionSet with 363 samples and 1,690,774 features specific to the stool bodysite
#' }
#'
#' \subsection{QinJ_2012.marker_abundance.stool}{
#'    An ExpressionSet with 363 samples and 132,934 features specific to the stool bodysite
#' }
#'
#' \subsection{QinJ_2012.marker_presence.stool}{
#'    An ExpressionSet with 363 samples and 125,127 features specific to the stool bodysite
#' }
#'
#' \subsection{QinJ_2012.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 363 samples and 1,588 features specific to the stool bodysite
#' }
#'
#' \subsection{QinJ_2012.pathabundance_relab.stool}{
#'    An ExpressionSet with 363 samples and 18,478 features specific to the stool bodysite
#' }
#'
#' \subsection{QinJ_2012.pathcoverage.stool}{
#'    An ExpressionSet with 363 samples and 18,478 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{QinJ_2012_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_bmi.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_bodysite.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_diabetic.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_height.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinJ_2012_weight.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    A metagenome-wide association study of gut microbiota in type 2 diabetes.
#' }
#'
#' \subsection{Author}{
#'    Qin J, Li Y, Cai Z, Li S, Zhu J, Zhang F, Liang S, Zhang W, Guan Y, Shen D, Peng Y, Zhang D, Jie Z, Wu W, Qin Y, Xue W, Li J, Han L, Lu D, Wu P, Dai Y, Sun X, Li Z, Tang A, Zhong S, Li X, Chen W, Xu R, Wang M, Feng Q, Gong M, Yu J, Zhang Y, Zhang M, Hansen T, Sanchez G, Raes J, Falony G, Okuda S, Almeida M, LeChatelier E, Renault P, Pons N, Batto JM, Zhang Z, Chen H, Yang R, Zheng W, Li S, Yang H, Wang J, Ehrlich SD, Nielsen R, Pedersen O, Kristiansen K, Wang J
#' }
#'
#' \subsection{Lab}{
#'    BGI-Shenzhen, Shenzhen 518083, China.
#' }
#'
#' \subsection{PMID}{
#'    23023125
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples QinJ_2012.genefamilies_relab.stool()
#' 
#' @name QinJ_2012 
NULL
