## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Taxonomic abundance data from the QinJ_2012 dataset
#' 
#' @aliases QinJ_2012.metaphlan_bugs_list.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{QinJ_2012.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 363 samples and 1,588 features specific to the stool bodysite
#' }
#' 
#' @source BGI-Shenzhen, Shenzhen 518083, China.
#' 
#' @seealso \code{\link{QinJ_2012.genefamilies_relab}}, \code{\link{QinJ_2012.marker_abundance}}, \code{\link{QinJ_2012.marker_presence}}, \code{\link{QinJ_2012.pathabundance_relab}}, \code{\link{QinJ_2012.pathcoverage}}
#' 
#' @examples QinJ_2012.metaphlan_bugs_list.stool()
#' 
#' @name QinJ_2012.metaphlan_bugs_list 
NULL
