## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the QinN_2014 study
#' 
#' @aliases QinN_2014.genefamilies_relab.stool QinN_2014.marker_abundance.stool QinN_2014.marker_presence.stool QinN_2014.metaphlan_bugs_list.stool QinN_2014.pathabundance_relab.stool QinN_2014.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{QinN_2014.genefamilies_relab.stool}{
#'    An ExpressionSet with 237 samples and 1,747,534 features specific to the stool bodysite
#' }
#'
#' \subsection{QinN_2014.marker_abundance.stool}{
#'    An ExpressionSet with 237 samples and 132,775 features specific to the stool bodysite
#' }
#'
#' \subsection{QinN_2014.marker_presence.stool}{
#'    An ExpressionSet with 237 samples and 126,097 features specific to the stool bodysite
#' }
#'
#' \subsection{QinN_2014.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 237 samples and 1,512 features specific to the stool bodysite
#' }
#'
#' \subsection{QinN_2014.pathabundance_relab.stool}{
#'    An ExpressionSet with 237 samples and 19,418 features specific to the stool bodysite
#' }
#'
#' \subsection{QinN_2014.pathcoverage.stool}{
#'    An ExpressionSet with 237 samples and 19,418 features specific to the stool bodysite
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{QinN_2014_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinN_2014_bmi.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinN_2014_bodysite.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinN_2014_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinN_2014_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{QinN_2014_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Alterations of the human gut microbiome in liver cirrhosis.
#' }
#'
#' \subsection{Author}{
#'    Qin N, Yang F, Li A, Prifti E, Chen Y, Shao L, Guo J, Le Chatelier E, Yao J, Wu L, Zhou J, Ni S, Liu L, Pons N, Batto JM, Kennedy SP, Leonard P, Yuan C, Ding W, Chen Y, Hu X, Zheng B, Qian G, Xu W, Ehrlich SD, Zheng S, Li L
#' }
#'
#' \subsection{Lab}{
#'    [1] State Key Laboratory for Diagnosis and Treatment of Infectious Disease, The First Affiliated Hospital, College of Medicine, Zhejiang University, 310003 Hangzhou, China [2] Collaborative Innovation Center for Diagnosis and Treatment of Infectious Diseases, Zhejiang University, 310003 Hangzhou, China [3].
#' }
#'
#' \subsection{PMID}{
#'    25079328
#' }
#' 
#' @seealso \code{\link{}}
#' 
#' @examples QinN_2014.genefamilies_relab.stool()
#' 
#' @name QinN_2014 
NULL
