## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Relabeled genefamilies data from the QinN_2014 dataset
#' 
#' @aliases QinN_2014.genefamilies_relab.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{QinN_2014.genefamilies_relab.stool}{
#'    An ExpressionSet with 237 samples and 1,747,534 features specific to the stool bodysite
#' }
#' 
#' @source [1] State Key Laboratory for Diagnosis and Treatment of Infectious Disease, The First Affiliated Hospital, College of Medicine, Zhejiang University, 310003 Hangzhou, China [2] Collaborative Innovation Center for Diagnosis and Treatment of Infectious Diseases, Zhejiang University, 310003 Hangzhou, China [3].
#' 
#' @seealso \code{\link{QinN_2014.marker_abundance}}, \code{\link{QinN_2014.marker_presence}}, \code{\link{QinN_2014.metaphlan_bugs_list}}, \code{\link{QinN_2014.pathabundance_relab}}, \code{\link{QinN_2014.pathcoverage}}
#' 
#' @name QinN_2014.genefamilies_relab 
NULL
