## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Marker presence data from the RampelliS_2015 dataset
#' 
#' @aliases RampelliS_2015.marker_presence.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{RampelliS_2015.marker_presence.stool}{
#'    An ExpressionSet with 38 samples and 47,456 features specific to the stool bodysite
#' }
#' 
#' @source Department of Pharmacy and Biotechnology, University of Bologna, Bologna 40126, Italy.
#' 
#' @seealso \code{\link{RampelliS_2015.genefamilies_relab}}, \code{\link{RampelliS_2015.marker_abundance}}, \code{\link{RampelliS_2015.metaphlan_bugs_list}}, \code{\link{RampelliS_2015.pathabundance_relab}}, \code{\link{RampelliS_2015.pathcoverage}}
#' 
#' @name RampelliS_2015.marker_presence 
NULL
