## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the RampelliS_2015 study
#' 
#' @aliases RampelliS_2015.genefamilies_relab.stool RampelliS_2015.marker_abundance.stool RampelliS_2015.marker_presence.stool RampelliS_2015.metaphlan_bugs_list.stool RampelliS_2015.pathabundance_relab.stool RampelliS_2015.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{RampelliS_2015.genefamilies_relab.stool}{
#'    An ExpressionSet with 38 samples and 788,640 features specific to the stool body site
#' }
#'
#' \subsection{RampelliS_2015.marker_abundance.stool}{
#'    An ExpressionSet with 38 samples and 50,394 features specific to the stool body site
#' }
#'
#' \subsection{RampelliS_2015.marker_presence.stool}{
#'    An ExpressionSet with 38 samples and 47,455 features specific to the stool body site
#' }
#'
#' \subsection{RampelliS_2015.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 38 samples and 727 features specific to the stool body site
#' }
#'
#' \subsection{RampelliS_2015.pathabundance_relab.stool}{
#'    An ExpressionSet with 38 samples and 6,798 features specific to the stool body site
#' }
#'
#' \subsection{RampelliS_2015.pathcoverage.stool}{
#'    An ExpressionSet with 38 samples and 6,798 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{RampelliS_2015_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RampelliS_2015_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RampelliS_2015_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RampelliS_2015_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Metagenome Sequencing of the Hadza Hunter-Gatherer Gut Microbiota.
#' }
#'
#' \subsection{Author}{
#'    Rampelli S, Schnorr SL, Consolandi C, Turroni S, Severgnini M, Peano C, Brigidi P, Crittenden AN, Henry AG, Candela M
#' }
#'
#' \subsection{Lab}{
#'    Department of Pharmacy and Biotechnology, University of Bologna, Bologna 40126, Italy.
#' }
#'
#' \subsection{PMID}{
#'    25981789
#' }
#' 
#' @examples RampelliS_2015.metaphlan_bugs_list.stool()
#' 
#' @name RampelliS_2015 
NULL
 