## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the RaymondF_2016 study
#' 
#' @aliases 20170526.RaymondF_2016.genefamilies_relab.stool 20170526.RaymondF_2016.marker_abundance.stool 20170526.RaymondF_2016.marker_presence.stool 20170526.RaymondF_2016.metaphlan_bugs_list.stool 20170526.RaymondF_2016.pathabundance_relab.stool 20170526.RaymondF_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{20170526.RaymondF_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 72 samples and 1,060,132 features specific to the stool body site
#' }
#'
#' \subsection{20170526.RaymondF_2016.marker_abundance.stool}{
#'    An ExpressionSet with 72 samples and 72,992 features specific to the stool body site
#' }
#'
#' \subsection{20170526.RaymondF_2016.marker_presence.stool}{
#'    An ExpressionSet with 72 samples and 70,705 features specific to the stool body site
#' }
#'
#' \subsection{20170526.RaymondF_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 72 samples and 834 features specific to the stool body site
#' }
#'
#' \subsection{20170526.RaymondF_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 72 samples and 8,562 features specific to the stool body site
#' }
#'
#' \subsection{20170526.RaymondF_2016.pathcoverage.stool}{
#'    An ExpressionSet with 72 samples and 8,562 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{RaymondF_2016_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RaymondF_2016_antibiotics_current_use.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RaymondF_2016_BMI.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RaymondF_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RaymondF_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{RaymondF_2016_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    The initial state of the human gut microbiome determines its reshaping by antibiotics.
#' }
#'
#' \subsection{Author}{
#'    Raymond F, Ouameur AA, Déraspe M, Iqbal N, Gingras H, Dridi B, Leprohon P, Plante PL, Giroux R, Bérubé NA, Frenette J, Boudreau DK, Simard JL, Chabot I, Domingo MC, Trottier S, Boissinot M, Huletsky A, Roy PH, Ouellette M, Bergeron MG, Corbeil J
#' }
#'
#' \subsection{Lab}{
#'    Centre de Recherche en Infectiologie, CHU de Quebec-Universite Laval, Quebec, Canada.
#' }
#'
#' \subsection{PMID}{
#'    26359913
#' }
#' 
#' @examples 20170526.RaymondF_2016.genefamilies_relab.stool()
#' 
#' @name RaymondF_2016 
NULL
 