## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the RaymondF_2016 study
#' 
#' @aliases RaymondF_2016.genefamilies_relab.stool RaymondF_2016.marker_abundance.stool RaymondF_2016.marker_presence.stool RaymondF_2016.metaphlan_bugs_list.stool RaymondF_2016.pathabundance_relab.stool RaymondF_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{RaymondF_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 72 samples and 1,060,132 features specific to the stool body site
#' }
#'
#' \subsection{RaymondF_2016.marker_abundance.stool}{
#'    An ExpressionSet with 72 samples and 72,992 features specific to the stool body site
#' }
#'
#' \subsection{RaymondF_2016.marker_presence.stool}{
#'    An ExpressionSet with 72 samples and 70,705 features specific to the stool body site
#' }
#'
#' \subsection{RaymondF_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 72 samples and 834 features specific to the stool body site
#' }
#'
#' \subsection{RaymondF_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 72 samples and 8,562 features specific to the stool body site
#' }
#'
#' \subsection{RaymondF_2016.pathcoverage.stool}{
#'    An ExpressionSet with 72 samples and 8,562 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    The initial state of the human gut microbiome determines its reshaping by antibiotics.
#' }
#'
#' \subsection{Author}{
#'    Raymond F, Ouameur AA, Déraspe M, Iqbal N, Gingras H, Dridi B, Leprohon P, Plante PL, Giroux R, Bérubé NA, Frenette J, Boudreau DK, Simard JL, Chabot I, Domingo MC, Trottier S, Boissinot M, Huletsky A, Roy PH, Ouellette M, Bergeron MG, Corbeil J
#' }
#'
#' \subsection{Lab}{
#'    [1] Centre de Recherche en Infectiologie, CHU de Quebec-Universite Laval, Quebec, Canada., [2] Institut National de Sante Publique du Quebec, Laboratoire de Sante Publique du Quebec, Montreal, Quebec, Canada.
#' }
#'
#' \subsection{PMID}{
#'    26359913
#' }
#' 
#' @examples `RaymondF_2016.metaphlan_bugs_list.stool`()
#' 
#' @name RaymondF_2016 
NULL
