## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the SchirmerM_2016 study
#' 
#' @aliases SchirmerM_2016.genefamilies_relab.stool SchirmerM_2016.marker_abundance.stool SchirmerM_2016.marker_presence.stool SchirmerM_2016.metaphlan_bugs_list.stool SchirmerM_2016.pathabundance_relab.stool SchirmerM_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{SchirmerM_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 471 samples and 1,396,085 features specific to the stool body site
#' }
#'
#' \subsection{SchirmerM_2016.marker_abundance.stool}{
#'    An ExpressionSet with 471 samples and 104,930 features specific to the stool body site
#' }
#'
#' \subsection{SchirmerM_2016.marker_presence.stool}{
#'    An ExpressionSet with 471 samples and 101,457 features specific to the stool body site
#' }
#'
#' \subsection{SchirmerM_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 471 samples and 1,177 features specific to the stool body site
#' }
#'
#' \subsection{SchirmerM_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 471 samples and 12,707 features specific to the stool body site
#' }
#'
#' \subsection{SchirmerM_2016.pathcoverage.stool}{
#'    An ExpressionSet with 471 samples and 12,707 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{SchirmerM_2016_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{SchirmerM_2016_antibiotics_current_use.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{SchirmerM_2016_BMI.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{SchirmerM_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{SchirmerM_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{SchirmerM_2016_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{SchirmerM_2016_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Linking the Human Gut Microbiome to Inflammatory Cytokine Production Capacity.
#' }
#'
#' \subsection{Author}{
#'    Schirmer M, Smeekens SP, Vlamakis H, Jaeger M, Oosting M, Franzosa EA, Horst RT, Jansen T, Jacobs L, Bonder MJ, Kurilshikov A, Fu J, Joosten LA, Zhernakova A, Huttenhower C, Wijmenga C, Netea MG, Xavier RJ
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    27984736
#' }
#' 
#' @examples SchirmerM_2016.metaphlan_bugs_list.stool()
#' 
#' @name SchirmerM_2016 
NULL
 