## generated by make_data_documentation(): do not edit by hand
## see source in data-raw/make_data_documentation.R
#' Data from the ShiB_2015 study
#'
#' @aliases ShiB_2015.genefamilies_relab.oralcavity ShiB_2015.marker_abundance.oralcavity ShiB_2015.marker_presence.oralcavity ShiB_2015.metaphlan_bugs_list.oralcavity ShiB_2015.pathabundance_relab.oralcavity 20181025.ShiB_2015.pathcoverage.oralcavity
#'
#' @section Datasets:
#'
#' \subsection{ShiB_2015.genefamilies_relab.oralcavity}{
#'    An ExpressionSet with 48 samples and 601,260 features specific to the oralcavity body site
#' }
#'
#' \subsection{ShiB_2015.marker_abundance.oralcavity}{
#'    An ExpressionSet with 48 samples and 56,520 features specific to the oralcavity body site
#' }
#'
#' \subsection{ShiB_2015.marker_presence.oralcavity}{
#'    An ExpressionSet with 48 samples and 55,414 features specific to the oralcavity body site
#' }
#'
#' \subsection{ShiB_2015.metaphlan_bugs_list.oralcavity}{
#'    An ExpressionSet with 48 samples and 729 features specific to the oralcavity body site
#' }
#'
#' \subsection{ShiB_2015.pathabundance_relab.oralcavity}{
#'    An ExpressionSet with 48 samples and 6,934 features specific to the oralcavity body site
#' }
#'
#' \subsection{20181025.ShiB_2015.pathcoverage.oralcavity}{
#'    An ExpressionSet with 48 samples and 6,934 features specific to the oralcavity body site
#' }
#'
#' @section Source:
#'
#' \subsection{Title}{
#'    Dynamic changes in the subgingival microbiome and their potential for diagnosis and prognosis of periodontitis.
#' }
#'
#' \subsection{Author}{
#'    Shi B, Chang M, Martin J, Mitreva M, Lux R, Klokkevold P, Sodergren E, Weinstock GM, Haake SK, Li H
#' }
#'
#' \subsection{Lab}{
#'    [1] Department of Molecular and Medical Pharmacology, Crump Institute for Molecular Imaging, David Geffen School of Medicine, UCLA, Los Angeles, California, USA., [2] Section of Periodontics, School of Dentistry, UCLA, Los Angeles, California, USA., [3] The Genome Institute, Washington University, St. Louis, Missouri, USA., [4] The Jackson Laboratory for Genomic Medicine, Farmington, Connecticut, USA., [5] huiying@mednet.ucla.edu.
#' }
#'
#' \subsection{PMID}{
#'    25691586
#' }
#'
#' @examples `ShiB_2015.metaphlan_bugs_list.oralcavity`()
#'
#' @name ShiB_2015
NULL
