## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Taxonomic abundance data from the TettAJ_2016 dataset
#' 
#' @aliases TettAJ_2016.metaphlan_bugs_list.left_elbow 
#' 
#' @section Datasets: 
#' 
#' \subsection{TettAJ_2016.metaphlan_bugs_list.left_elbow}{
#'    An ExpressionSet with 26 samples and 1,004 features specific to the left_elbow bodysite
#' }
#'        