## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the TettAJ_2019_b study
#' 
#' @aliases TettAJ_2019_b.genefamilies_relab.stool TettAJ_2019_b.marker_abundance.stool TettAJ_2019_b.marker_presence.stool TettAJ_2019_b.metaphlan_bugs_list.stool TettAJ_2019_b.pathabundance_relab.stool TettAJ_2019_b.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{TettAJ_2019_b.genefamilies_relab.stool}{
#'    An ExpressionSet with 44 samples and 1,004,301 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_b.marker_abundance.stool}{
#'    An ExpressionSet with 44 samples and 70,004 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_b.marker_presence.stool}{
#'    An ExpressionSet with 44 samples and 67,823 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_b.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 44 samples and 849 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_b.pathabundance_relab.stool}{
#'    An ExpressionSet with 44 samples and 10,531 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_b.pathcoverage.stool}{
#'    An ExpressionSet with 44 samples and 10,531 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples TettAJ_2019_b.metaphlan_bugs_list.stool()
#' 
#' @name TettAJ_2019_b 
NULL
