## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Pathcoverage data from the TettAJ_2016 dataset
#' 
#' @aliases TettAJ_2016.pathcoverage.left_ear 
#' 
#' @section Datasets: 
#' 
#' \subsection{TettAJ_2016.pathcoverage.left_ear}{
#'    An ExpressionSet with 22 samples and 21,899 features specific to the left_ear bodysite
#' }
#' 
#' @source 
#' 
#' @seealso \code{\link{TettAJ_2016.genefamilies_relab}}, \code{\link{TettAJ_2016.genefamilies_relab}}, \code{\link{TettAJ_2016.genefamilies_relab}}, \code{\link{TettAJ_2016.genefamilies_relab}}, \code{\link{TettAJ_2016.marker_abundance}}, \code{\link{TettAJ_2016.marker_abundance}}, \code{\link{TettAJ_2016.marker_abundance}}, \code{\link{TettAJ_2016.marker_abundance}}, \code{\link{TettAJ_2016.marker_presence}}, \code{\link{TettAJ_2016.marker_presence}}, \code{\link{TettAJ_2016.marker_presence}}, \code{\link{TettAJ_2016.marker_presence}}, \code{\link{TettAJ_2016.metaphlan_bugs_list}}, \code{\link{TettAJ_2016.metaphlan_bugs_list}}, \code{\link{TettAJ_2016.metaphlan_bugs_list}}, \code{\link{TettAJ_2016.metaphlan_bugs_list}}, \code{\link{TettAJ_2016.pathabundance_relab}}, \code{\link{TettAJ_2016.pathabundance_relab}}, \code{\link{TettAJ_2016.pathabundance_relab}}, \code{\link{TettAJ_2016.pathabundance_relab}}
#' 
#' @name TettAJ_2016.pathcoverage 
NULL
