## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the TettAJ_2019_a study
#' 
#' @aliases TettAJ_2019_a.genefamilies_relab.stool TettAJ_2019_a.marker_abundance.stool TettAJ_2019_a.marker_presence.stool TettAJ_2019_a.metaphlan_bugs_list.stool TettAJ_2019_a.pathabundance_relab.stool TettAJ_2019_a.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{TettAJ_2019_a.genefamilies_relab.stool}{
#'    An ExpressionSet with 68 samples and 1,173,786 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_a.marker_abundance.stool}{
#'    An ExpressionSet with 68 samples and 75,815 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_a.marker_presence.stool}{
#'    An ExpressionSet with 68 samples and 73,480 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_a.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 68 samples and 960 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_a.pathabundance_relab.stool}{
#'    An ExpressionSet with 68 samples and 11,310 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_a.pathcoverage.stool}{
#'    An ExpressionSet with 68 samples and 11,310 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples TettAJ_2019_a.metaphlan_bugs_list.stool()
#' 
#' @name TettAJ_2019_a 
NULL
