## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the TettAJ_2019_c study
#' 
#' @aliases TettAJ_2019_c.genefamilies_relab.stool TettAJ_2019_c.marker_abundance.stool TettAJ_2019_c.marker_presence.stool TettAJ_2019_c.metaphlan_bugs_list.stool TettAJ_2019_c.pathabundance_relab.stool TettAJ_2019_c.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{TettAJ_2019_c.genefamilies_relab.stool}{
#'    An ExpressionSet with 50 samples and 1,023,154 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_c.marker_abundance.stool}{
#'    An ExpressionSet with 50 samples and 62,479 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_c.marker_presence.stool}{
#'    An ExpressionSet with 50 samples and 60,773 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_c.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 50 samples and 866 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_c.pathabundance_relab.stool}{
#'    An ExpressionSet with 50 samples and 9,250 features specific to the stool body site
#' }
#'
#' \subsection{TettAJ_2019_c.pathcoverage.stool}{
#'    An ExpressionSet with 50 samples and 9,250 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples TettAJ_2019_c.metaphlan_bugs_list.stool()
#' 
#' @name TettAJ_2019_c 
NULL
