## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the TettAJ_2016 study
#' 
#' @aliases TettAJ_2016.genefamilies_relab.skin TettAJ_2016.marker_abundance.skin TettAJ_2016.marker_presence.skin TettAJ_2016.metaphlan_bugs_list.skin TettAJ_2016.pathabundance_relab.skin TettAJ_2016.pathcoverage.skin 
#' 
#' @section Datasets: 
#' 
#' \subsection{TettAJ_2016.genefamilies_relab.skin}{
#'    An ExpressionSet with 97 samples and 1,183,853 features specific to the skin body site
#' }
#'
#' \subsection{TettAJ_2016.marker_abundance.skin}{
#'    An ExpressionSet with 97 samples and 64,039 features specific to the skin body site
#' }
#'
#' \subsection{TettAJ_2016.marker_presence.skin}{
#'    An ExpressionSet with 97 samples and 57,428 features specific to the skin body site
#' }
#'
#' \subsection{TettAJ_2016.metaphlan_bugs_list.skin}{
#'    An ExpressionSet with 97 samples and 1,004 features specific to the skin body site
#' }
#'
#' \subsection{TettAJ_2016.pathabundance_relab.skin}{
#'    An ExpressionSet with 97 samples and 21,899 features specific to the skin body site
#' }
#'
#' \subsection{TettAJ_2016.pathcoverage.skin}{
#'    An ExpressionSet with 97 samples and 21,899 features specific to the skin body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{TettAJ_2016_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{TettAJ_2016_antibiotics_current_use.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{TettAJ_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{TettAJ_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{TettAJ_2016_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{TettAJ_2016_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples TettAJ_2016.genefamilies_relab.skin()
#' 
#' @name TettAJ_2016 
NULL
 