## generated by make_documentation(): do not edit by hand
## see source in inst/scripts/make-documentation.R
#' Relabeled genefamilies data from the TettAJ_2016 dataset
#'
#' @aliases TettAJ_2016.genefamilies_relab.left_ear TettAJ_2016.genefamilies_relab.left_elbow TettAJ_2016.genefamilies_relab.right_ear TettAJ_2016.genefamilies_relab.right_elbow
#'
#' @section Datasets:
#'
#' \subsection{TettAJ_2016.genefamilies_relab.left_ear}{
#'    An ExpressionSet with 22 samples and 1,183,854 features specific to the left_ear bodysite
#' }
#'
#' \subsection{TettAJ_2016.genefamilies_relab.left_elbow}{
#'    An ExpressionSet with 26 samples and 1,183,854 features specific to the left_elbow bodysite
#' }
#'
#' \subsection{TettAJ_2016.genefamilies_relab.right_ear}{
#'    An ExpressionSet with 26 samples and 1,183,854 features specific to the right_ear bodysite
#' }
#'
#' \subsection{TettAJ_2016.genefamilies_relab.right_elbow}{
#'    An ExpressionSet with 23 samples and 1,183,854 features specific to the right_elbow bodysite
#' }
#'
#' @seealso \code{\link{TettAJ_2016.marker_abundance}}, \code{\link{TettAJ_2016.marker_presence}}, \code{\link{TettAJ_2016.metaphlan_bugs_list}}, \code{\link{TettAJ_2016.pathabundance_relab}}, \code{\link{TettAJ_2016.pathcoverage}}
#'
#' @examples TettAJ_2016.genefamilies_relab.left_ear()
#'
#' @name TettAJ_2016.genefamilies_relab
NULL
