## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the ThomasAM_2018b study
#' 
#' @aliases ThomasAM_2018b.genefamilies_relab.stool ThomasAM_2018b.marker_abundance.stool ThomasAM_2018b.marker_presence.stool ThomasAM_2018b.metaphlan_bugs_list.stool ThomasAM_2018b.pathabundance_relab.stool ThomasAM_2018b.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{ThomasAM_2018b.genefamilies_relab.stool}{
#'    An ExpressionSet with 60 samples and 1,401,350 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018b.marker_abundance.stool}{
#'    An ExpressionSet with 60 samples and 93,190 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018b.marker_presence.stool}{
#'    An ExpressionSet with 60 samples and 91,404 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018b.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 60 samples and 1,079 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018b.pathabundance_relab.stool}{
#'    An ExpressionSet with 60 samples and 8,107 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018b.pathcoverage.stool}{
#'    An ExpressionSet with 60 samples and 8,107 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples ThomasAM_2018b.metaphlan_bugs_list.stool()
#' 
#' @name ThomasAM_2018b 
NULL
