## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the ThomasAM_2018a study
#' 
#' @aliases ThomasAM_2018a.genefamilies_relab.stool ThomasAM_2018a.marker_abundance.stool ThomasAM_2018a.marker_presence.stool ThomasAM_2018a.metaphlan_bugs_list.stool ThomasAM_2018a.pathabundance_relab.stool ThomasAM_2018a.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{ThomasAM_2018a.genefamilies_relab.stool}{
#'    An ExpressionSet with 80 samples and 1,324,452 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018a.marker_abundance.stool}{
#'    An ExpressionSet with 80 samples and 88,476 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018a.marker_presence.stool}{
#'    An ExpressionSet with 80 samples and 86,326 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018a.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 80 samples and 1,162 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018a.pathabundance_relab.stool}{
#'    An ExpressionSet with 80 samples and 8,227 features specific to the stool body site
#' }
#'
#' \subsection{ThomasAM_2018a.pathcoverage.stool}{
#'    An ExpressionSet with 80 samples and 8,227 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    NA
#' }
#'
#' \subsection{Author}{
#'    NA
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    NA
#' }
#' 
#' @examples ThomasAM_2018a.metaphlan_bugs_list.stool()
#' 
#' @name ThomasAM_2018a 
NULL
