## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the VatanenT_2016 study
#' 
#' @aliases VatanenT_2016.genefamilies_relab.stool VatanenT_2016.marker_abundance.stool VatanenT_2016.marker_presence.stool VatanenT_2016.metaphlan_bugs_list.stool VatanenT_2016.pathabundance_relab.stool VatanenT_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{VatanenT_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 785 samples and 1,719,634 features specific to the stool body site
#' }
#'
#' \subsection{VatanenT_2016.marker_abundance.stool}{
#'    An ExpressionSet with 785 samples and 135,979 features specific to the stool body site
#' }
#'
#' \subsection{VatanenT_2016.marker_presence.stool}{
#'    An ExpressionSet with 785 samples and 131,625 features specific to the stool body site
#' }
#'
#' \subsection{VatanenT_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 785 samples and 1,584 features specific to the stool body site
#' }
#'
#' \subsection{VatanenT_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 785 samples and 19,236 features specific to the stool body site
#' }
#'
#' \subsection{VatanenT_2016.pathcoverage.stool}{
#'    An ExpressionSet with 785 samples and 19,236 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Variation in Microbiome LPS Immunogenicity Contributes to Autoimmunity in Humans.
#' }
#'
#' \subsection{Author}{
#'    Vatanen T, Kostic AD, d'Hennezel E, Siljander H, Franzosa EA, Yassour M, Kolde R, Vlamakis H, Arthur TD, Hämäläinen AM, Peet A, Tillmann V, Uibo R, Mokurov S, Dorshakova N, Ilonen J, Virtanen SM, Szabo SJ, Porter JA, Lähdesmäki H, Huttenhower C, Gevers D, Cullen TW, Knip M, Xavier RJ
#' }
#'
#' \subsection{Lab}{
#'    NA
#' }
#'
#' \subsection{PMID}{
#'    27259157
#' }
#' 
#' @examples VatanenT_2016.metaphlan_bugs_list.stool()
#' 
#' @name VatanenT_2016 
NULL
