## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the VincentC_2016 study
#' 
#' @aliases VincentC_2016.genefamilies_relab.stool VincentC_2016.marker_abundance.stool VincentC_2016.marker_presence.stool VincentC_2016.metaphlan_bugs_list.stool VincentC_2016.pathabundance_relab.stool VincentC_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{VincentC_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 229 samples and 1,513,277 features specific to the stool body site
#' }
#'
#' \subsection{VincentC_2016.marker_abundance.stool}{
#'    An ExpressionSet with 229 samples and 116,377 features specific to the stool body site
#' }
#'
#' \subsection{VincentC_2016.marker_presence.stool}{
#'    An ExpressionSet with 229 samples and 110,951 features specific to the stool body site
#' }
#'
#' \subsection{VincentC_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 229 samples and 1,452 features specific to the stool body site
#' }
#'
#' \subsection{VincentC_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 229 samples and 16,254 features specific to the stool body site
#' }
#'
#' \subsection{VincentC_2016.pathcoverage.stool}{
#'    An ExpressionSet with 229 samples and 16,254 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{VincentC_2016_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VincentC_2016_antibiotics_current_use.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VincentC_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VincentC_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VincentC_2016_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VincentC_2016_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Bloom and bust: intestinal microbiota dynamics in response to hospital exposures and Clostridium difficile colonization or infection.
#' }
#'
#' \subsection{Author}{
#'    Vincent C, Miller MA, Edens TJ, Mehrotra S, Dewar K, Manges AR
#' }
#'
#' \subsection{Lab}{
#'    Department of Microbiology and Immunology, McGill University, Montreal, Quebec, Canada.
#' }
#'
#' \subsection{PMID}{
#'    26975510
#' }
#' 
#' @examples VincentC_2016.genefamilies_relab.stool()
#' 
#' @name VincentC_2016 
NULL
 