## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the VogtmannE_2016 study
#' 
#' @aliases VogtmannE_2016.genefamilies_relab.stool VogtmannE_2016.marker_abundance.stool VogtmannE_2016.marker_presence.stool VogtmannE_2016.metaphlan_bugs_list.stool VogtmannE_2016.pathabundance_relab.stool VogtmannE_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{VogtmannE_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 110 samples and 1,511,515 features specific to the stool body site
#' }
#'
#' \subsection{VogtmannE_2016.marker_abundance.stool}{
#'    An ExpressionSet with 110 samples and 110,990 features specific to the stool body site
#' }
#'
#' \subsection{VogtmannE_2016.marker_presence.stool}{
#'    An ExpressionSet with 110 samples and 107,190 features specific to the stool body site
#' }
#'
#' \subsection{VogtmannE_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 110 samples and 1,296 features specific to the stool body site
#' }
#'
#' \subsection{VogtmannE_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 110 samples and 14,809 features specific to the stool body site
#' }
#'
#' \subsection{VogtmannE_2016.pathcoverage.stool}{
#'    An ExpressionSet with 110 samples and 14,809 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Colorectal Cancer and the Human Gut Microbiome: Reproducibility with Whole-Genome Shotgun Sequencing.
#' }
#'
#' \subsection{Author}{
#'    Vogtmann E, Hua X, Zeller G, Sunagawa S, Voigt AY, Hercog R, Goedert JJ, Shi J, Bork P, Sinha R
#' }
#'
#' \subsection{Lab}{
#'    [1] Division of Cancer Epidemiology &amp; Genetics, National Cancer Institute, Bethesda, Maryland, United States of America., [2] Division of Cancer Prevention, National Cancer Institute, Bethesda, Maryland, United States of America., [3] Structural and Computational Biology Unit, European Molecular Biology Laboratory, Heidelberg, Germany., [4] Department of Applied Tumor Biology, Institute of Pathology, University Hospital Heidelberg, Heidelberg, Germany., [5] Clinical Cooperation Unit Applied Tumor Biology, German Cancer Research Center (DKFZ), Heidelberg, Germany., [6] Molecular Medicine Partnership Unit (MMPU), University Hospital Heidelberg and European Molecular Biology Laboratory, Heidelberg, Germany., [7] Genomics Core Facility, European Molecular Biology Laboratory, Heidelberg, Germany., [8] Max Delbruck Centre for Molecular Medicine, Berlin, Germany., [9] Department of Bioinformatics Biocenter, University of Wurzburg, Wurzburg, Germany.
#' }
#'
#' \subsection{PMID}{
#'    27171425
#' }
#' 
#' @examples VogtmannE_2016.metaphlan_bugs_list.stool()
#' 
#' @name VogtmannE_2016 
NULL
