## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the VogtmannE_2016 study
#' 
#' @aliases 20170526.VogtmannE_2016.genefamilies_relab.stool 20170526.VogtmannE_2016.marker_abundance.stool 20170526.VogtmannE_2016.marker_presence.stool 20170526.VogtmannE_2016.metaphlan_bugs_list.stool 20170526.VogtmannE_2016.pathabundance_relab.stool 20170526.VogtmannE_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{20170526.VogtmannE_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 110 samples and 2,229,881 features specific to the stool body site
#' }
#'
#' \subsection{20170526.VogtmannE_2016.marker_abundance.stool}{
#'    An ExpressionSet with 110 samples and 1,009,074 features specific to the stool body site
#' }
#'
#' \subsection{20170526.VogtmannE_2016.marker_presence.stool}{
#'    An ExpressionSet with 110 samples and 986,069 features specific to the stool body site
#' }
#'
#' \subsection{20170526.VogtmannE_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 110 samples and 11,432 features specific to the stool body site
#' }
#'
#' \subsection{20170526.VogtmannE_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 110 samples and 18,706 features specific to the stool body site
#' }
#'
#' \subsection{20170526.VogtmannE_2016.pathcoverage.stool}{
#'    An ExpressionSet with 110 samples and 18,706 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{VogtmannE_2016_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VogtmannE_2016_BMI.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VogtmannE_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VogtmannE_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VogtmannE_2016_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{VogtmannE_2016_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Colorectal Cancer and the Human Gut Microbiome: Reproducibility with Whole-Genome Shotgun Sequencing.
#' }
#'
#' \subsection{Author}{
#'    Vogtmann E, Hua X, Zeller G, Sunagawa S, Voigt AY, Hercog R, Goedert JJ, Shi J, Bork P, Sinha R
#' }
#'
#' \subsection{Lab}{
#'    Division of Cancer Epidemiology &amp; Genetics, National Cancer Institute, Bethesda, Maryland, United States of America.
#' }
#'
#' \subsection{PMID}{
#'    27171425
#' }
#' 
#' @examples 20170526.VogtmannE_2016.genefamilies_relab.stool()
#' 
#' @name VogtmannE_2016 
NULL
 