## generated by make_data_documentation(): do not edit by hand
## see source in data-raw/make_data_documentation.R
#' Data from the WenC_2017 study
#'
#' @aliases WenC_2017.genefamilies_relab.stool WenC_2017.marker_abundance.stool WenC_2017.marker_presence.stool WenC_2017.metaphlan_bugs_list.stool WenC_2017.pathabundance_relab.stool WenC_2017.pathcoverage.stool
#'
#' @details Note that WenC_2017 is deprecated and will be made defunct, use ChengpingW_2017 instead.
#' @section Datasets:
#'
#' \subsection{WenC_2017.genefamilies_relab.stool}{
#'    An ExpressionSet with 97 samples and 1,160,257 features specific to the stool body site
#' }
#'
#' \subsection{WenC_2017.marker_abundance.stool}{
#'    An ExpressionSet with 97 samples and 89,660 features specific to the stool body site
#' }
#'
#' \subsection{WenC_2017.marker_presence.stool}{
#'    An ExpressionSet with 97 samples and 83,333 features specific to the stool body site
#' }
#'
#' \subsection{WenC_2017.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 97 samples and 1,075 features specific to the stool body site
#' }
#'
#' \subsection{WenC_2017.pathabundance_relab.stool}{
#'    An ExpressionSet with 97 samples and 11,713 features specific to the stool body site
#' }
#'
#' \subsection{WenC_2017.pathcoverage.stool}{
#'    An ExpressionSet with 97 samples and 11,713 features specific to the stool body site
#' }
#'
#' @section Source:
#'
#' \subsection{Title}{
#'    Quantitative metagenomics reveals unique gut microbiome biomarkers in ankylosing spondylitis.
#' }
#'
#' \subsection{Author}{
#'    Wen C, Zheng Z, Shao T, Liu L, Xie Z, Le Chatelier E, He Z, Zhong W, Fan Y, Zhang L, Li H, Wu C, Hu C, Xu Q, Zhou J, Cai S, Wang D, Huang Y, Breban M, Qin N, Ehrlich SD
#' }
#'
#' \subsection{Lab}{
#'    [1] Institute of Basic Research in Clinical Medicine, College of Basic Medical Science, Zhejiang Chinese Medical University, Hangzhou, 310053, China. wengcp@163.com., [2] Realbio Genomics Institute, Shanghai, 200123, China., [3] Institute of Basic Research in Clinical Medicine, College of Basic Medical Science, Zhejiang Chinese Medical University, Hangzhou, 310053, China., [4] State Key Laboratory for Diagnosis and Treatment of Infectious Diseases, Department of Infectious Diseases, the First Affiliated College of Medicine, Zhejiang University, Hangzhou, 310003, China., [5] Collaborative Innovation Center for Diagnosis and Treatment of Infectious Diseases, Zhejiang University, Hangzhou, 310003, China., [6] INRA, Institut National de la Recherche Agronomique, Metagenopolis, Jouy en Josas, 78350, France., [7] Rheumatology Division, Ambroise-Pare Hospital, AP-HP, 9, avenue Charles-de-Gaulle, 92100, Boulogne-Billancourt, France., [8] Realbio Genomics Institute, Shanghai, 200123, China. qinnan001@126.com., [9] State Key Laboratory for Diagnosis and Treatment of Infectious Diseases, Department of Infectious Diseases, the First Affiliated College of Medicine, Zhejiang University, Hangzhou, 310003, China. qinnan001@126.com., [10] Collaborative Innovation Center for Diagnosis and Treatment of Infectious Diseases, Zhejiang University, Hangzhou, 310003, China. qinnan001@126.com., [11] INRA, Institut National de la Recherche Agronomique, Metagenopolis, Jouy en Josas, 78350, France. dusko.ehrlich@jouy.inra.fr., [12] King's College London, Centre for Host-Microbiome Interactions, Dental Institute Central Office, Guy's Hospital, London Bridge, London, SE1 9RT, UK. dusko.ehrlich@jouy.inra.fr.
#' }
#'
#' \subsection{PMID}{
#'    28750650
#' }
#'
#' @examples `WenC_2017.metaphlan_bugs_list.stool`()
#'
#' @name WenC_2017
NULL
