## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the XieH_2016 study
#' 
#' @aliases 20170526.XieH_2016.genefamilies_relab.stool 20170526.XieH_2016.marker_abundance.stool 20170526.XieH_2016.marker_presence.stool 20170526.XieH_2016.metaphlan_bugs_list.stool 20170526.XieH_2016.pathabundance_relab.stool 20170526.XieH_2016.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{20170526.XieH_2016.genefamilies_relab.stool}{
#'    An ExpressionSet with 250 samples and 1,743,159 features specific to the stool body site
#' }
#'
#' \subsection{20170526.XieH_2016.marker_abundance.stool}{
#'    An ExpressionSet with 250 samples and 142,530 features specific to the stool body site
#' }
#'
#' \subsection{20170526.XieH_2016.marker_presence.stool}{
#'    An ExpressionSet with 250 samples and 129,776 features specific to the stool body site
#' }
#'
#' \subsection{20170526.XieH_2016.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 250 samples and 1,551 features specific to the stool body site
#' }
#'
#' \subsection{20170526.XieH_2016.pathabundance_relab.stool}{
#'    An ExpressionSet with 250 samples and 15,880 features specific to the stool body site
#' }
#'
#' \subsection{20170526.XieH_2016.pathcoverage.stool}{
#'    An ExpressionSet with 250 samples and 15,880 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{XieH_2016_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{XieH_2016_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{XieH_2016_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{XieH_2016_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Shotgun Metagenomics of 250 Adult Twins Reveals Genetic and Environmental Impacts on the Gut Microbiome.
#' }
#'
#' \subsection{Author}{
#'    Xie H, Guo R, Zhong H, Feng Q, Lan Z, Qin B, Ward KJ, Jackson MA, Xia Y, Chen X, Chen B, Xia H, Xu C, Li F, Xu X, Al-Aama JY, Yang H, Wang J, Kristiansen K, Wang J, Steves CJ, Bell JT, Li J, Spector TD, Jia H
#' }
#'
#' \subsection{Lab}{
#'    BGI-Shenzhen, Shenzhen 518083, China; China National Genebank-Shenzhen, BGI-Shenzhen, Shenzhen 518083, China.
#' }
#'
#' \subsection{PMID}{
#'    27818083
#' }
#' 
#' @examples 20170526.XieH_2016.genefamilies_relab.stool()
#' 
#' @name XieH_2016 
NULL
 