## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the YeZ_2018 study
#' 
#' @aliases YeZ_2018.genefamilies_relab.stool YeZ_2018.marker_abundance.stool YeZ_2018.marker_presence.stool YeZ_2018.metaphlan_bugs_list.stool YeZ_2018.pathabundance_relab.stool YeZ_2018.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{YeZ_2018.genefamilies_relab.stool}{
#'    An ExpressionSet with 65 samples and 1,030,667 features specific to the stool body site
#' }
#'
#' \subsection{YeZ_2018.marker_abundance.stool}{
#'    An ExpressionSet with 65 samples and 62,179 features specific to the stool body site
#' }
#'
#' \subsection{YeZ_2018.marker_presence.stool}{
#'    An ExpressionSet with 65 samples and 58,357 features specific to the stool body site
#' }
#'
#' \subsection{YeZ_2018.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 65 samples and 784 features specific to the stool body site
#' }
#'
#' \subsection{YeZ_2018.pathabundance_relab.stool}{
#'    An ExpressionSet with 65 samples and 5,812 features specific to the stool body site
#' }
#'
#' \subsection{YeZ_2018.pathcoverage.stool}{
#'    An ExpressionSet with 65 samples and 5,812 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    A metagenomic study of the gut microbiome in Behcet's disease.
#' }
#'
#' \subsection{Author}{
#'    Ye Z, Zhang N, Wu C, Zhang X, Wang Q, Huang X, Du L, Cao Q, Tang J, Zhou C, Hou S, He Y, Xu Q, Xiong X, Kijlstra A, Qin N, Yang P
#' }
#'
#' \subsection{Lab}{
#'    [1] The First Affiliated Hospital of Chongqing Medical University, Chongqing Key Lab of Ophthalmology, Chongqing Eye Institute, Chongqing, 400016, China., [2] Realbio Genomics Institute, Shanghai, 201114, China., [3] Beijing Institute of Ophthalmology, Beijing Tongren Eye Center, Beijing Tongren Hospital, Capital Medical University, Beijing Ophthalmology &amp; Visual Sciences Key Lab, Beijing, 100730, China., [4] Shenzhen Jinrui Biotechnology, Co. Ltd., Shenzhen, 518000, China., [5] University Eye Clinic Maastricht, Maastricht, The Netherlands., [6] Shanghai Tenth People's Hospital Affiliated to Tongji University, Shanghai, 200072, China., [7] The First Affiliated Hospital of Chongqing Medical University, Chongqing Key Lab of Ophthalmology, Chongqing Eye Institute, Chongqing, 400016, China. peizengycmu@126.com.
#' }
#'
#' \subsection{PMID}{
#'    30077182
#' }
#' 
#' @examples YeZ_2018.metaphlan_bugs_list.stool()
#' 
#' @name YeZ_2018 
NULL
