## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the YuJ_2015 study
#' 
#' @aliases YuJ_2015.genefamilies_relab.stool YuJ_2015.marker_abundance.stool YuJ_2015.marker_presence.stool YuJ_2015.metaphlan_bugs_list.stool YuJ_2015.pathabundance_relab.stool YuJ_2015.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{YuJ_2015.genefamilies_relab.stool}{
#'    An ExpressionSet with 128 samples and 1,532,931 features specific to the stool body site
#' }
#'
#' \subsection{YuJ_2015.marker_abundance.stool}{
#'    An ExpressionSet with 128 samples and 125,243 features specific to the stool body site
#' }
#'
#' \subsection{YuJ_2015.marker_presence.stool}{
#'    An ExpressionSet with 128 samples and 117,525 features specific to the stool body site
#' }
#'
#' \subsection{YuJ_2015.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 128 samples and 1,405 features specific to the stool body site
#' }
#'
#' \subsection{YuJ_2015.pathabundance_relab.stool}{
#'    An ExpressionSet with 128 samples and 15,487 features specific to the stool body site
#' }
#'
#' \subsection{YuJ_2015.pathcoverage.stool}{
#'    An ExpressionSet with 128 samples and 15,487 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{YuJ_2015_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{YuJ_2015_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{YuJ_2015_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Metagenomic analysis of faecal microbiome as a tool towards targeted non-invasive biomarkers for colorectal cancer.
#' }
#'
#' \subsection{Author}{
#'    Yu J, Feng Q, Wong SH, Zhang D, Liang QY, Qin Y, Tang L, Zhao H, Stenvang J, Li Y, Wang X, Xu X, Chen N, Wu WK, Al-Aama J, Nielsen HJ, Kiilerich P, Jensen BA, Yau TO, Lan Z, Jia H, Li J, Xiao L, Lam TY, Ng SC, Cheng AS, Wong VW, Chan FK, Xu X, Yang H, Madsen L, Datz C, Tilg H, Wang J, Brünner N, Kristiansen K, Arumugam M, Sung JJ, Wang J
#' }
#'
#' \subsection{Lab}{
#'    Department of Medicine &amp; Therapeutics, State Key Laboratory of Digestive Disease, Institute of Digestive Disease, LKS Institute of Health Sciences, CUHK Shenzhen Research Institute, The Chinese University of Hong Kong, Hong Kong.
#' }
#'
#' \subsection{PMID}{
#'    26408641
#' }
#' 
#' @examples YuJ_2015.genefamilies_relab.stool()
#' 
#' @name YuJ_2015 
NULL
 