## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the ZeeviD_2015 study
#' 
#' @aliases ZeeviD_2015.genefamilies_relab.stool ZeeviD_2015.marker_abundance.stool ZeeviD_2015.marker_presence.stool ZeeviD_2015.metaphlan_bugs_list.stool ZeeviD_2015.pathabundance_relab.stool ZeeviD_2015.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{ZeeviD_2015.genefamilies_relab.stool}{
#'    An ExpressionSet with 900 samples and 1,870,320 features specific to the stool body site
#' }
#'
#' \subsection{ZeeviD_2015.marker_abundance.stool}{
#'    An ExpressionSet with 900 samples and 619,348 features specific to the stool body site
#' }
#'
#' \subsection{ZeeviD_2015.marker_presence.stool}{
#'    An ExpressionSet with 900 samples and 476,217 features specific to the stool body site
#' }
#'
#' \subsection{ZeeviD_2015.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 900 samples and 4,744 features specific to the stool body site
#' }
#'
#' \subsection{ZeeviD_2015.pathabundance_relab.stool}{
#'    An ExpressionSet with 900 samples and 19,764 features specific to the stool body site
#' }
#'
#' \subsection{ZeeviD_2015.pathcoverage.stool}{
#'    An ExpressionSet with 900 samples and 19,764 features specific to the stool body site
#' }
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Personalized Nutrition by Prediction of Glycemic Responses.
#' }
#'
#' \subsection{Author}{
#'    Zeevi D, Korem T, Zmora N, Israeli D, Rothschild D, Weinberger A, Ben-Yacov O, Lador D, Avnit-Sagi T, Lotan-Pompan M, Suez J, Mahdi JA, Matot E, Malka G, Kosower N, Rein M, Zilberman-Schapira G, Dohnalová L, Pevsner-Fischer M, Bikovsky R, Halpern Z, Elinav E, Segal E
#' }
#'
#' \subsection{Lab}{
#'    [1] Department of Computer Science and Applied Mathematics, Weizmann Institute of Science, Rehovot 7610001, Israel; Department of Molecular Cell Biology, Weizmann Institute of Science, Rehovot 7610001, Israel., [2] Immunology Department, Weizmann Institute of Science, Rehovot 7610001, Israel; Internal Medicine Department, Tel Aviv Sourasky Medical Center, Tel Aviv 6423906, Israel; Research Center for Digestive Tract and Liver Diseases, Tel Aviv Sourasky Medical Center, Sackler Faculty of Medicine, Tel Aviv University, Tel Aviv 6423906, Israel., [3] Day Care Unit and the Laboratory of Imaging and Brain Stimulation, Kfar Shaul Hospital, Jerusalem Center for Mental Health, Jerusalem 9106000, Israel., [4] Immunology Department, Weizmann Institute of Science, Rehovot 7610001, Israel., [5] Research Center for Digestive Tract and Liver Diseases, Tel Aviv Sourasky Medical Center, Sackler Faculty of Medicine, Tel Aviv University, Tel Aviv 6423906, Israel; Digestive Center, Tel Aviv Sourasky Medical Center, Tel Aviv 6423906, Israel., [6] Immunology Department, Weizmann Institute of Science, Rehovot 7610001, Israel. Electronic address: eran.elinav@weizmann.ac.il., [7] Department of Computer Science and Applied Mathematics, Weizmann Institute of Science, Rehovot 7610001, Israel; Department of Molecular Cell Biology, Weizmann Institute of Science, Rehovot 7610001, Israel. Electronic address: eran.segal@weizmann.ac.il.
#' }
#'
#' \subsection{PMID}{
#'    26590418
#' }
#' 
#' @examples ZeeviD_2015.metaphlan_bugs_list.stool()
#' 
#' @name ZeeviD_2015 
NULL
