## generated by make_documentation(): do not edit by hand 
## see source in inst/scripts/make-documentation.R 
#' Marker presence data from the ZellerG_2014 dataset
#' 
#' @aliases ZellerG_2014.marker_presence.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{ZellerG_2014.marker_presence.stool}{
#'    An ExpressionSet with 156 samples and 126,622 features specific to the stool bodysite
#' }
#' 
#' @source Structural and Computational Biology Unit, European Molecular Biology Laboratory, Heidelberg, Germany.
#' 
#' @seealso \code{\link{ZellerG_2014.genefamilies_relab}}, \code{\link{ZellerG_2014.marker_abundance}}, \code{\link{ZellerG_2014.metaphlan_bugs_list}}, \code{\link{ZellerG_2014.pathabundance_relab}}, \code{\link{ZellerG_2014.pathcoverage}}
#' 
#' @name ZellerG_2014.marker_presence 
NULL
