## generated by make_data_documentation(): do not edit by hand 
## see source in data-raw/make_data_documentation.R 
#' Data from the ZellerG_2014 study
#' 
#' @aliases ZellerG_2014.genefamilies_relab.stool ZellerG_2014.marker_abundance.stool ZellerG_2014.marker_presence.stool ZellerG_2014.metaphlan_bugs_list.stool ZellerG_2014.pathabundance_relab.stool ZellerG_2014.pathcoverage.stool 
#' 
#' @section Datasets: 
#' 
#' \subsection{ZellerG_2014.genefamilies_relab.stool}{
#'    An ExpressionSet with 199 samples and 2,040,556 features specific to the stool body site
#' }
#'
#' \subsection{ZellerG_2014.marker_abundance.stool}{
#'    An ExpressionSet with 199 samples and 828,890 features specific to the stool body site
#' }
#'
#' \subsection{ZellerG_2014.marker_presence.stool}{
#'    An ExpressionSet with 199 samples and 735,085 features specific to the stool body site
#' }
#'
#' \subsection{ZellerG_2014.metaphlan_bugs_list.stool}{
#'    An ExpressionSet with 199 samples and 10,503 features specific to the stool body site
#' }
#'
#' \subsection{ZellerG_2014.pathabundance_relab.stool}{
#'    An ExpressionSet with 199 samples and 19,367 features specific to the stool body site
#' }
#'
#' \subsection{ZellerG_2014.pathcoverage.stool}{
#'    An ExpressionSet with 199 samples and 19,367 features specific to the stool body site
#' }
#' 
#' @section Exploratory Data Analysis: 
#' 
#' \if{html}{\figure{ZellerG_2014_age.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ZellerG_2014_BMI.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ZellerG_2014_body_site.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ZellerG_2014_country.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ZellerG_2014_disease.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#'
#' \if{html}{\figure{ZellerG_2014_gender.png}{options: width="100\%"}}
#' \if{latex}{An EDA figure is available in the HTML documentation}
#'
#' 
#' @section Source: 
#' 
#' \subsection{Title}{
#'    Potential of fecal microbiota for early-stage detection of colorectal cancer.
#' }
#'
#' \subsection{Author}{
#'    Zeller G, Tap J, Voigt AY, Sunagawa S, Kultima JR, Costea PI, Amiot A, Böhm J, Brunetti F, Habermann N, Hercog R, Koch M, Luciani A, Mende DR, Schneider MA, Schrotz-King P, Tournigand C, Tran Van Nhieu J, Yamada T, Zimmermann J, Benes V, Kloor M, Ulrich CM, von Knebel Doeberitz M, Sobhani I, Bork P
#' }
#'
#' \subsection{Lab}{
#'    Structural and Computational Biology Unit, European Molecular Biology Laboratory, Heidelberg, Germany.
#' }
#'
#' \subsection{PMID}{
#'    25432777
#' }
#' 
#' @examples ZellerG_2014.metaphlan_bugs_list.stool()
#' 
#' @name ZellerG_2014 
NULL
 