name: BiocCheck

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  bioccheck:
    runs-on: ubuntu-latest
    container:
      image: bioconductor/bioconductor_docker:devel

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install R Package Dependencies
        run: |
          Rscript -e "BiocManager::install(c('BiocCheck', 'covr', 'lintr'))"

      - name: Run BiocCheck
        run: |
          BiocCheck::BiocCheck(
              ".",
              `no-check-install-self` = TRUE,
          )
        shell: Rscript {0}

      - name: Run R CMD check
        run: R CMD check .

      - name: Test Coverage
        run: Rscript -e "covr::codecov()"

      - name: Lint Code
        run: Rscript -e "lintr::lint_package()"

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage-badge.svg
